### ISSUE TITLE
Acorn Crash When I've Tried to Move From Priority View Back to Map View

### ISSUE THREAD

**Issue by marcelomichelsohn** [lightningrodlabs/acorn#10]
system: macbook pro 2012, running Catalina 10.15.7
![Acorn - Crash](https://user-images.githubusercontent.com/36304848/117575378-e0166580-b0b7-11eb-92f8-10de2d05aa02.png)

**Comment by Connoropolous** [comment]
Thanks for reporting! If you can click 'show stack trace' as well that's helpful. 

does it continually do this, or did it just do this once?

**Comment by marcelomichelsohn** [comment]
It just did it once. Now it is working fine. I don't know if it happened because I've created a second project or because I deleted my profile picture URL and left it blank.

**Comment by Connoropolous** [comment]
K. I will try messing around with the profile picture as that seems as a possible source of trouble

**Comment by pegahvaezi** [comment]
@marcelomichelsohn let us know if this issue still happens to you in the latest release (v1.0.2-alpha). For now I'm closing this issue.
