### ISSUE TITLE
+ table view

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#102]
There is a whole new route/view, within ProjectView, called TableView. 

Designs: 
https://xd.adobe.com/view/82dc191d-8943-4adf-a854-1d7819d2e306-d78f/

- [ ] search and filters in the table header (persistable to localstorage)
- [ ] the table header
- [ ] individual table row items

**Comment by Connoropolous** [comment]
Designs: 
https://xd.adobe.com/view/82dc191d-8943-4adf-a854-1d7819d2e306-d78f/

**Comment by weswalla** [comment]
# rough conceptual outline
## component outline
![table-view-component-outline](https://user-images.githubusercontent.com/39413655/162544030-ad864e72-183e-42f9-9e8e-e58d54cfe532.png)
```
<ProjectView>
	<TableView>
		<FilterSelector/>
		<OutcomeTable/>
	</TableView>
</ProjectView>
```
## filter logic
![filter-logic-outline](https://user-images.githubusercontent.com/39413655/162544032-1ce2ca57-c518-442f-910f-55fb38a08cac.png)
```
<OutcomeTable
	outcomes={filterTable(outcomes, filter)}
></OutcomeTable>

filterTable(outcomes, filter): {
	// returns the filtered list of outcomes to go in the table
}
```

Filter object:
```
{
	keywordOrId: string,
	myCardsOnly: boolean,
	achievementStatus: [string],
	scope: [string],
	assignees: [string],
	tags: [string]
}
```

**Comment by weswalla** [comment]
@Connoropolous any thoughts on this?

**Comment by Connoropolous** [comment]
Nice!

You can remove myCardsOnly and instead just use the assignees field. Also note that typescript syntax would be string[]
{
	keywordOrId: string,
	myCardsOnly: boolean,
	achievementStatus: [string],
	scope: [string],
	assignees: [string],
	tags: [string]
}

**Comment by Connoropolous** [comment]
The component outline looks good, just note that we are reorganizing footer component and it likely won't be there.
