### ISSUE TITLE
new component system

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#107]
build this in the Storybook. 

Depends on #105 

- [x] Typography component

**TableView**
- [x] FilterSearch
- [x] FilterDropdown
- [x] FilterButton
- [x] OutcomeListItem
- [x] ProgressIndicator
- [x] ExpandChevron

**ExpandedView**
- [x] ButtonAction
- [x] ButtonToggleSwitch 
- [x] Checkbox
- [x] ButtonCheckbox
- [x] SelectDropdown
- [x] ChecklistItem
- [x] Checklist
- [x] AvatarsList
- [x] Tag
- [x] TagsList
- [ ] TagPicker
- [ ] GithubLink
- [x] EvLeftColumn
- [x] EvMiddleColumn
- [x] EvRightColumn
- [x] DescendantsAchievementStatus
- [ ] ReadOnlyInfo
- [ ] MetadataWithLabel
    - [ ] withIcon
    - [ ]  Children (slot for metadata)
- [x] ButtonTabIcon
- [ ] MarkdownInput
- [x] CloseButton

**Comments**
- [x] CommentPosted (use the ones we have)
- [x] CommentInput (use the ones we have)

**Comment by pegahvaezi** [comment]
- [ ] Typography component

**TableView**
- [ ] FilterSearch
- [ ] FilterDropdown
- [x] FilterButton
- [ ] OutcomeListItem
- [ ] ProgressIndicator
- [ ] ExpandChevron

**Expanded View**
- [x] ButtonAction
- [x] Checkbox
- [x] ButtonCheckbox
- [x] Dropdown
- [x] ChecklistItem
- [x] Checklist
- [ ] AvatarsList (base)
- [ ] AssigneesList (has AvatarsList)
- [ ] MembersList (has AvatarsList)
- [ ] MetadataWithLabel
    - [ ] withIcon
    - [ ]  Children (slot for metadata)
- [ ] TabIconButton
- [ ] GithubLink
- [ ] MarkdownInput
- [ ] CloseButton
- [ ] ReadOnlyInfo
**Comments**
- [ ] CommentPosted (use the ones we have)
- [ ] CommentInput
