### ISSUE TITLE
Crashed When Going Back Into Project

### ISSUE THREAD

**Issue by marcelomichelsohn** [lightningrodlabs/acorn#11]
I was working on a project. Clicked on the top left corner on the "acorn" word. Then tried to go back to project one and it crashed.
![Acorn Crash on going back to project](https://user-images.githubusercontent.com/36304848/117575610-f8d34b00-b0b8-11eb-89a2-acf8b470ae8d.png)

**Comment by Connoropolous** [comment]
thanks for reporting!
We will need to figure out what the steps to reproduce this are... I will see what I can do, but if you can provide any more details such as 
- was this first launch of the app? 
- how many goals and edges (links) were created? 
- was it a collaborative project? 
- did you set up an image avatar for yourself?

**Comment by marcelomichelsohn** [comment]
So now, it is not crashing anymore. I've created a second project and I am switching between both.
When I reported the issue it was my first launch of the app. It was a collaborative project I was invited to join. It had 5 goals and 3 of them were linked. I didn't see my avatar  image and after that I deleted the URL with my image and could see my initials.

**Comment by pegahvaezi** [comment]
@marcelomichelsohn let us know if this issue still happens to you in the latest release (v1.0.2-alpha). For now I'm closing this issue.
