### ISSUE TITLE
+- header

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#110]
- [ ] bring the component that relates to 'switching between views within a project' into the Header. It is currently in the footer. 
- [ ] remove the guidebook and replace it with an external link

**Comment by TechSupport26** [comment]
Request
Can the guidebook be added back in or is it gone forever?
Having it there as a quick guide and the link as the complete knowledge base.
I do like the new documentation but the guidebook could be a small summary for some features.
