### ISSUE TITLE
Cannot load appimage on my ARCH linux.

### ISSUE THREAD

**Issue by adamth0mps0n** [lightningrodlabs/acorn#121]
Error report is as follows  --> Will try an restart and see if that fixes anything
-_____________________________________-
name = 'holochain-runner'
operating_system = 'unix:Unknown'
crate_version = '0.0.35'
explanation = '''
Panic occurred in file 'src/embedded_runner.rs' at line 163
'''
cause = 'Could not initialize Conductor from configuration: InterfaceError(WebsocketError(Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" })))'
method = 'Panic'
backtrace = '''

   0: 0x5628e3496bf1 - <unresolved>
   1: 0x5628e3496ce3 - <unresolved>
   2: 0x5628e3672bd6 - <unresolved>
   3: 0x5628e38bdc48 - <unresolved>
   4: 0x5628e38c75be - <unresolved>
   5: 0x5628e37d594d - <unresolved>
   6: 0x5628e3882c7d - <unresolved>
   7: 0x5628e3951e03 - <unresolved>
   8: 0x5628e388dc39 - <unresolved>
   9: 0x5628e517376b - <unresolved>
  10: 0x5628e3883512 - <unresolved>
  11: 0x7ff0bcb9c310 - __libc_start_call_main
  12: 0x7ff0bcb9c3c1 - __libc_start_main@GLIBC_2.2.5
  13: 0x5628e349739a - <unresolved>
  14:        0x0 - <unresolved>'''

**Comment by adamth0mps0n** [comment]
A reboot did not help.. 
Terminal error gives me this 
________________________________________
(acorn:5642): Gtk-WARNING **: 23:11:37.940: Theme parsing error: gtk-dark.css:5827:11: Expected a length
holochain > 1
holochain >
holochain > ###HOLOCHAIN_SETUP###
holochain > ###ADMIN_PORT:1235###
holochain > ###HOLOCHAIN_SETUP_END###
holochain > DATASTORE_PATH: /home/adam/.config/acorn/databases-2
holochain >  KEYSTORE_PATH: /home/adam/.config/acorn/keystore-2
holochain >            UID: None
holochain > Recognized a keypair, using that...
holochain > An existing configuration and identity was found, using that.
holochain >      APP_WS_PORT: 8889
holochain > INSTALLED_APP_ID: main-app
holochain > EMBEDDED_HOLOCHAIN_IS_READY
holochain > 7
^CKilling holochain sub processes...
Killing lair-keystore sub processes...
waiting...
holochain > ctrlc got shutdown signal
holochain > successfully sent shutdown signal to embedded-holochain-runner
holochain >
lair-keystore closed with code:  null
holochain-runner closed with code:  0
killed all lair-keystore sub processes
killed all holochain sub processes
Killing sub-processes DONE.
___________________________________________
Despite a fresh reboot it seems that the old version is interfering with the new one.. I will have to flush the Database and keystore in the .config directory.

**Comment by Connoropolous** [comment]
@adamth0mps0n did you get this resolved? trying to follow the status of this issue...

**Comment by adamth0mps0n** [comment]
> 

Nope.  Deleting the config file fixed the error message but I am still unable to run the app.. I just get a blank screen.
Following is the output from the terminal.

holochain > 0
holochain > 
holochain > ###HOLOCHAIN_SETUP###
holochain > ###ADMIN_PORT:1235###
holochain > ###HOLOCHAIN_SETUP_END###
holochain > DATASTORE_PATH: /home/adam/.config/acorn/databases-2
holochain >  KEYSTORE_PATH: /home/adam/.config/acorn/keystore-2
holochain >            UID: None
holochain > Don't recognize you, so generating a new identity for you...
holochain > 2
holochain > Your new key pair is generated, the public key is: AgentPubKey(uhCAk-749rSKrecYGNEG6etWmLdRCJpF7jFBquhxaFWfYQFj_jh38)
holochain > There is no app installed, so starting fresh...
holochain > continuing with the installation...
holochain > 3
holochain > 4
holochain > Installed, now enabling...
holochain > 5
holochain > 6
holochain > Enabled.
holochain >      APP_WS_PORT: 8889
holochain > INSTALLED_APP_ID: main-app
holochain > EMBEDDED_HOLOCHAIN_IS_READY
holochain > 7

**Comment by Connoropolous** [comment]
@adamth0mps0n 
I have a feeling that this issue may be related to the rather lagging version of Holochain that Acorn is currently released on, and a degree of incompatibility with a piece of infrastructure we're dependent on which may have been updated. I hope it will resolve itself via doing an update. let's stay in touch about it, I will message here with any relevant updates

**Comment by adamth0mps0n** [comment]
The new version of Acorn fixed everything.
All is well.
