### ISSUE TITLE
v0.9.0-alpha3 will not import projects from v0.6.0-alpha

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#123]
I have exported 2 acorn projects from v0.6.0 (JSON download) and have tried to import them to v0.9.0 and it never loaded the project. it was going for about 12 hours.

I was able to import a project from v0.9.0 to 0.9.0 but it did not keep the entry point I put in one of the cards.

**Comment by Connoropolous** [comment]
@TechSupport26 
v0.9.0 (when it is officially released, which it isn't yet) brings breaking changes, and we haven't yet (and may not) provide the 'import' functionality for prior versions. 

Do you have real world projects depending on this functionality?

**Comment by TechSupport26** [comment]
I don't have any projects that depend on this functionality I was just trying out the latest release. When I went back to version 0.6.0 all the projects were still there. I just did not want to assume that this was something unintentional.

**Comment by Connoropolous** [comment]
Ah I see. Thanks for reporting, it did actually bring it to attention so that we can communicate that this version won't be able to import historical ones.

**Comment by adamth0mps0n** [comment]
> @TechSupport26 v0.9.0 (when it is officially released, which it isn't yet) brings breaking changes, and we haven't yet (and may not) provide the 'import' functionality for prior versions.
> 
> Do you have real world projects depending on this functionality?

I have a bunch.. But its not the end of the world to recreate them. Just time consuming.. 
Perhaps I could do an export from V0.90 and compare the JSON.. It might be simple to manually edit and upload.

**Comment by Connoropolous** [comment]
Oh hm. I will take at the very least a look and consider the work involved to facilitate that automatically. If extensive, we are likely to pass, but if its not extensive, we will implement, and I will report here to let you know!

**Comment by adamth0mps0n** [comment]
That would be awesome.. it's an alpha app so totally ok if its too hard. I didn't expect things to work nearly as well as they do.

**Comment by pegahvaezi** [comment]
We made a decision not to support backwards compatibility for the new releases importing projects from prior to v1.0.2-alpha, so closing this issue here.
