### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#127]
I have found a way to crash Acorn reliably
You select a card shift select or just click on one to highlight it, copy and paste, try and create a child card and boom.
Only one card has to be selected but you can have multiple cards selected
You can click on either of the 2 connection-connector-blue-dot (the blue doth above and below a card)

Only works reliably if your zoom is at 100% (it does work at other levels but I have found 100% to be the most reliable) You can change the zoom in/out in the View tab toolbar or by doing the shortcuts.

Acorn will add the cards to the right of the highest card.

https://user-images.githubusercontent.com/65631811/171513275-e1efc38a-189c-4747-9afa-77641e9d4d76.mp4

Cannot read property 'x' of undefined

TypeError: Cannot read property 'x' of undefined
    at df (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:351:397271)
    at Qa (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:57951)
    at ws (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:104333)
    at xc (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:96859)
    at _c (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:96784)
    at fc (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:93807)
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:45339
    at t.unstable_runWithPriority (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:317:3844)
    at Ko (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:45048)
    at Xo (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:45284)

_Originally posted by @TechSupport26 in https://github.com/lightningrodlabs/acorn/issues/125#issuecomment-1144201101_

**Comment by Connoropolous** [comment]
@TechSupport26  you originally posted this and I see that it was an issue relating to copy-paste. Can you confirm whether this is still an issue?  :)

**Comment by TechSupport26** [comment]
I will have to check tomorrow and let you know.

**Comment by Connoropolous** [comment]
all good. thanks!

**Comment by TechSupport26** [comment]
If I copy and paste multiple cards they lose their previous structure.

https://user-images.githubusercontent.com/65631811/190272473-971c3fe1-746d-42f6-8402-32ee80838fa5.mp4

For a brief moment, the card will change to this after closing the card.
![image](https://user-images.githubusercontent.com/65631811/190273419-688cc213-05c3-497a-8313-0d4ea057f381.png)

Before pressing the escape key to close a card text boxes should save what has been written.

https://user-images.githubusercontent.com/65631811/190273249-1cf1151d-dd02-4f57-aad0-3c8187439a41.mp4

You can only add 2 cards to a parent card when using the Connect function, any additional cards will not connect. Preview works fine.

https://user-images.githubusercontent.com/65631811/190274039-8b6b19e6-b724-46c1-b45c-9af14f49b48b.mp4

If you can't delete the connecting line between 2 cards then if you make a new parent card for the child card you will have 2 parent cards as Acorn does not delete this connection. (Refreshing does not update the cards.)
You also can't delete the connecting lines between the original 2 cards but you can for the 2nd parent card. Depends on the card as I deleted one of them successfully.

If you get a card that does not disconnect itself from its parent before going to a new one you get this.
![image](https://user-images.githubusercontent.com/65631811/190275941-62833146-8914-4dda-ab36-a087e2d4ee3e.png)
![image](https://user-images.githubusercontent.com/65631811/190277210-e09bf9a0-f991-4bc8-8d00-d645a9352c83.png)

Demo
https://user-images.githubusercontent.com/65631811/190275466-20a405e9-f359-49e8-b572-78c5e4aef805.mp4

The setup used. (This works for some cards and has not worked consistently every 2-3 tries)
https://user-images.githubusercontent.com/65631811/190275432-7acec6b2-91af-406c-940f-a4a1106c2fd8.mp4

As a result, the bottom card now has 12 child cards but it is just the same card.

https://user-images.githubusercontent.com/65631811/190277898-49f4c140-63eb-42b0-8baa-a9ef8537f2bb.mp4

To answer your original question I am not able to copy/paste cards in the same way as before. I will keep on trying and let you know.

**Comment by TechSupport26** [comment]
Looks like I missed something.

https://user-images.githubusercontent.com/65631811/190279124-df73248e-bfea-4573-9302-4d63f3210c8f.mp4

```
Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:351:262787
    at Array.filter (<anonymous>)
    at e (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:351:262771)
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:351:262848
    at Array.map (<anonymous>)
    at e (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:351:262824)
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:351:262848
    at Array.map (<anonymous>)
    at e (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:351:262824)
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:351:262848
```

**Comment by Connoropolous** [comment]
we are going to close this issue based on the original issue being fixed, but then we are going to look into your comments @TechSupport26 and file new issues accordingly.

**Comment by TechSupport26** [comment]
I have been able to create a card with a second parent card in v2.1.1-alpha I am looking into how I achieved this but it either has to do with a second user or creating a lot of delay diving time to add a second parent card. I will update this comment if or when I find something.

**Comment by pegahvaezi** [comment]
This replication of Outcome cards gaining two parents on v2.1.1-alpha seems to be an edge case (hard to replicate scenario), which we are not currently prioritizing. If the two parent issue happens with a more normal use then let us know and we'll look into it further.

**Comment by TechSupport26** [comment]
You can duplicate cards as shown in the video. I don't think that any action is needed, just something that I came across.
One card stays visible while the other is hidden in the map view and can be seen from the card above or in the table view. otherwise, they have the same card number and any change made to one affects the other. It looks like a ghost card but there is a gap for the card in the map view.

https://user-images.githubusercontent.com/65631811/206053513-0c491ad1-77ff-4b82-8c7f-b5138e858fc2.mp4
