### ISSUE TITLE
Feature Request: copy-paste between projects

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#128]
Is it possible to implement copying and pasting cards to different projects?

_Originally posted by @TechSupport26 in https://github.com/lightningrodlabs/acorn/issues/125#issuecomment-1144201101_

**Comment by Connoropolous** [comment]
FYI @TechSupport26 that copy-pasting between projects still isn't possibly, but that you CAN copy-paste within a project.

**Comment by TechSupport26** [comment]
I will make an issue later if I can find consistancy with copying and pasting text as when I do this Acorn will make a card. Also Acorn did crash alot when I did this.

**Comment by Connoropolous** [comment]
new tracking issue for this is #258
