### ISSUE TITLE
Acorn crashing while adding child cards

### ISSUE THREAD

**Issue by tansnowman** [lightningrodlabs/acorn#13]
I have been experiencing issues when I try to add a child card, and now I can't add any new cards at all.

I have rebooted the program a few times, and am still experiencing the issue.

**Comment by Connoropolous** [comment]
Hi!

Can you press Cmd-Option-I and you will see an additional console... search the upper menu of that for 'Console'. Can you take a screenshot of anything in red that appears there?

**Comment by Connoropolous** [comment]
or alternatively is it actually crashing? can you click on 'show stack trace' and post what it says?

**Comment by tansnowman** [comment]
Looks like it was mainly the two errors, but there was also one other.

<img width="552" alt="Screen Shot 2021-05-09 at 3 32 26 PM" src="https://user-images.githubusercontent.com/83926039/117587596-fe8e5800-b0db-11eb-8d32-7c8539c1142f.png">
<img width="555" alt="Screen Shot 2021-05-09 at 3 31 47 PM" src="https://user-images.githubusercontent.com/83926039/117587590-fa623a80-b0db-11eb-8ecc-6bb4aa0848ef.png">

**Comment by tansnowman** [comment]
It wasn't actually crashing. Just getting the error message that it crashed.

**Comment by Connoropolous** [comment]
thanks, can you describe a bit about
- which version of MacOS you're on
- how many projects you created
- how many goals did you create roughly before it started to not respond
- what were you doing right before it stopped working
-

**Comment by Connoropolous** [comment]
thanks, that's helpful. I should be able to reproduce

**Comment by tansnowman** [comment]
So glad I can help. I am honored to be a part of helping work out the bugs. Finally experiencing and testing a real, live HApp is quite exhilarating!

Keep it up!

**Comment by Connoropolous** [comment]
@tansnowman 

are you able to help with additional details on this? 
Is it still happening to you? Are you able to reproduce? 

If you can reproduce, can you grab a little screencapture?

**Comment by tansnowman** [comment]
Hey again, thanks for your patience hearing back from me. I haven’t tried lately, but I will give it a go, and let you know what I’m experiencing.

I’ll be in touch. Cheers!

**Comment by pegahvaezi** [comment]
@tansnowman let us know if this issue still happens to you in the latest release (v1.0.2-alpha). For now I'm closing this issue.
