### ISSUE TITLE
hover over card in map view to reveal full text of title

### ISSUE THREAD

**Issue by weswalla** [lightningrodlabs/acorn#130]
some outcome titles are cut in the map view because they are too long, ending in '...' It would be helpful to be able to read the full title quickly without entering expanded view. One way to do this would be to hover the cursor over the card, which could reveal the entire title.

**Comment by TechSupport26** [comment]
Perhaps it could be implemented by clicking on a card once to highlight it causing the card to expand so you can see more of the text.

**Comment by Connoropolous** [comment]
closed in https://github.com/lightningrodlabs/acorn/releases/tag/v2.1.0-alpha
