### ISSUE TITLE
Link does not stay in the Add a GitHub Issue or pull request link text box

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#135]
If you add a link to the Add a GitHub Issue or pull request link text box you have to press the return/enter key for it to stay there.
Can that be changed so once it has been added/edited the link stays there?

**Comment by TechSupport26** [comment]
A different request...

To close a card you have to press the close button. An addition to that could be to click outside of the expanded view to close the card.

**Comment by pegahvaezi** [comment]
Hi @TechSupport26! 

- Re: GitHub link - for now you'd need to press enter/return key to finish adding a GitHub link. In a future version we'll be adding the option to be able to finish adding a link also by clicking anywhere outside the link field.

- Re: closing expanded view on click outside/escape key - we will play with this requested behaviour and if it does not intervene with other UX details will add this!

**Comment by TechSupport26** [comment]
Both features have been implemented quite nicely in v1.1.0
Looking great.

**Comment by TechSupport26** [comment]
I was wondering if Project Settings and Invite members to project could be added to closing the expanded view by click outside/escape key.

**Comment by pegahvaezi** [comment]
Yes we will be improving these UX details as we go. Priority is given to 'high traffic' areas first!

**Comment by TechSupport26** [comment]
Should I reopen this or leave as is?

**Comment by pegahvaezi** [comment]
You can leave it as is - we have it noted.
