### ISSUE TITLE
Exiting a project leads to the main screen failing to load my projects

### ISSUE THREAD

**Issue by bierlingm** [lightningrodlabs/acorn#136]
OS: macOS Monterey 12.4 (M1 Max)

Steps to reproduce: open Acorn, enter a project, exit a project

Screenshot:
<img width="2032" alt="Screen Shot 2022-06-12 at 4 27 19 PM" src="https://user-images.githubusercontent.com/9335771/173237974-e1da6809-28bb-46cc-9397-43c30648702f.png">

**Comment by Connoropolous** [comment]
this could potentially be to a known issue where the websocket disconnects after a period of elapses time, and does not reconnect. can you imagine this being possible in your case? Or does this occur immediately during startup, after a fresh startup?

**Comment by bierlingm** [comment]
It very likely is what you describe since this only happens when it has been running for a while. No issue when I open it initially or close a project shortly after opening Acorn itself.

Is there a way I can find out whether this is the correct diagnosis?

Is there anything else I should do, or can we close this reasonably?

**Comment by Connoropolous** [comment]
Ah yep. That's very likely to be. We can leave it open for now as others might encounter it.

**Comment by Connoropolous** [comment]
We have it in our roadmap as an urgent fix

**Comment by pegahvaezi** [comment]
Hi @bierlingm would you be able to try the latest release (v1.1.0-alpha) and let us know if you still face the same issue? We believe to have it fixed in this new release.

**Comment by Connoropolous** [comment]
We are marking this one as closed, but will re-open it if we see the issue occur again
