### ISSUE TITLE
After computer sleeps, websocket connections may disconnect, but the UI is not aware

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#14]
This leads to symptoms like the Projects showing as being in the 'sync queue' because the error catcher is not specific enough.

I should try to fix this soon

**Comment by pegahvaezi** [comment]
@Connoropolous is this issue fixed in the v1.0.2-alpha?

**Comment by Connoropolous** [comment]
no, we still have this issue.

**Comment by pegahvaezi** [comment]
We believe this issue to be fixed for 1.1.0-alpha version, but also we are keeping an eye for it.

**Comment by Connoropolous** [comment]
thanks Drew. re-opening

**Comment by TechSupport26** [comment]
I am also experiencing this, only slightly differently.
If I have a project open after a time other users aren't automatically shown as online until I refresh the page.

**Comment by Connoropolous** [comment]
this shouldn't be an issue anymore. We'll need clearer 'steps to reproduce' in order to have any luck fixing something like this.
