### ISSUE TITLE
The Task list writing box has an extra line

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#144]
The "Add a checklist item" style has one extra line after you create the first Task setting the cursor below the check box on a new line.
![image](https://user-images.githubusercontent.com/65631811/177986441-7f9ac518-52f5-449d-843e-3983e85db9c0.png)

To reproduce go to the Task List and create a new checklist item.
After adding some text press the return key to create a new checklist item.
You should be one line below the checkbox.
Pressing the up arrow or clicking above the bottom line will take you up a line.
Pressing the backspace key will remove the line and will grey the Add a checklist Item box.

I have not found a way around this.

Version 1.0.3-alpha

**Comment by Connoropolous** [comment]
Thanks for reporting, we are able to reproduce this issue. We will issue a fix in the next release, which will likely come quite soon, as we had some other minor issues with 1.0.3-alpha so we decided not to announce it.

**Comment by Connoropolous** [comment]
This is fixed in the brand new v1.0.4-alpha release!
