### ISSUE TITLE
Skip the sign up process.

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#150]
You can skip the sign up process in 1.0.3 by clicking on the acorn button in the top left.
This allows you to join and create projects. Some UI does not show up and the user counter goes up after you join a project. You can edit the project using the available UI.

Works in Windows and MacOS (Testing linux in a day or so)

![Screen Shot 2022-07-26 at 2 39 42 pm](https://user-images.githubusercontent.com/65631811/180925683-3622c0cd-8bc0-4fde-b771-a11e16954041.png)

![Screen Shot 2022-07-26 at 2 41 17 pm](https://user-images.githubusercontent.com/65631811/180925590-5aaf0aba-826e-47ed-9653-b9c099bf2242.png)

https://user-images.githubusercontent.com/65631811/180925599-11fc31b9-93a2-4889-8dba-5910601ab2bd.mov

**Comment by Connoropolous** [comment]
good catch @TechSupport26 . This is something we should fix.

**Comment by pegahvaezi** [comment]
This bug has been fixed in 1.1.0-alpha release - the logo is not clickable anymore before creation of profile.

**Comment by TechSupport26** [comment]
Something to note, It is possible to remove the `run-update-screen-wrapper` element and click on the Acorn logo causing a crash. This happens any time there is a `-wrapper` that overlays the main `screen-wrapper`
I think that this would be an edge case if you want to open this issue as this would only happen if you muck around in the developer tools, something that a regular user would not likely do.

https://github.com/lightningrodlabs/acorn/assets/65631811/ca2714b9-25fa-4480-89a1-3524880b2ff8
