### ISSUE TITLE
Add scrolling to Task List and Children List inside of a card

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#154]
If you have more than 13 children in a card the ones after will be hidden with the 14th being half visible. (Unless there is a secret scrolling technique that I don't know about you won't be able to see the rest.)

![image](https://user-images.githubusercontent.com/65631811/187795329-c5a81938-1612-41da-b571-695488d6a06d.png)
![image](https://user-images.githubusercontent.com/65631811/187795585-32e0d6c2-f24f-422f-b4b3-3735a3efecf9.png)

**Comment by pegahvaezi** [comment]
Thanks for catching the bug! We'll look into it.

**Comment by Connoropolous** [comment]
This is fixed in v2.0.0, out now.
