### ISSUE TITLE
Windows unexpected failure to start the app

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#158]
Something that has come up a few times for me is after I log in to my computer and I start to run applications. During this time when there are limited processing resources, Acorn will not load and gets stuck on the Loading . . . screen and if I refresh (Ctrl R/Ctrl Shift R) I get stuck at Setting Up Holochain . . .

Here is a video if at all helpful. (You can fast forward most of it as my computer is just loading applications)

From restarting https://streamable.com/piytms
After startup (I think this one is a bit better as it is shorter but it does not show Acorn running from when I executed it)
https://user-images.githubusercontent.com/65631811/189008579-86a8cf60-0548-495a-affe-fd4e8229d25a.mp4

I don't think that this is much of an issue as you can just run Acorn again and it will work. (I believe that this happened on previous versions I just never reported it)

- Here is the output when I run it from cmd

```
C:\Users\zephd\AppData\Roaming\Microsoft\Windows\Start Menu\Programs>start acorn

C:\Users\zephd\AppData\Roaming\Microsoft\Windows\Start Menu\Programs>
holochain > Looking for passphrase piped to stdin
holochain > Found passphrase, continuing...
holochain > 1
holochain stderr err > Well, this is embarrassing.

holochain-runner had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "C:\Users\zephd\AppData\Local\Temp\report-7e8855d9-e1ea-49ee-8e1a-ca453c0089cd.toml". Submit an issue or email with the subject of "holochain-runner Crash Report" and include the report as an attachment.

- Authors: Connor Turland <connor@sprillow.com>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!

an unhandled error occurred: Error: Well, this is embarrassing.

holochain-runner had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "C:\Users\zephd\AppData\Local\Temp\report-7e8855d9-e1ea-49ee-8e1a-ca453c0089cd.toml". Submit an issue or email with the subject of "holochain-runner Crash Report" and include the report as an attachment.

- Authors: Connor Turland <connor@sprillow.com>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!

    at Socket.<anonymous> (C:\Users\zephd\AppData\Local\Programs\acorn\resources\app.asar\node_modules\@sprillow-connor\electron-holochain\dist\src\holochain.js:192:33)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
holochain >
holochain-runner closed with code:  101
```

- And the report file

```
name = 'holochain-runner'
operating_system = 'windows'
crate_version = '0.0.40'
explanation = '''
Panic occurred in file 'src\embedded_runner.rs' at line 166
'''
cause = 'Could not initialize Conductor from configuration: Other({"error":"The system cannot find the file specified. (os error 2)"})'
method = 'Panic'
backtrace = '''

   0: 0x7ff65066f149 - <unresolved>
   1: 0x7ff65087f095 - <unresolved>
   2: 0x7ff65087f1a3 - <unresolved>
   3: 0x7ff64e961732 - <unresolved>
   4: 0x7ff64ea6cf05 - <unresolved>
   5: 0x7ff64ea70c40 - <unresolved>
   6: 0x7ff64eae3fe9 - <unresolved>
   7: 0x7ff64ea09b81 - <unresolved>
   8: 0x7ff64ea46fa6 - <unresolved>
   9: 0x7ff64e9ee9ec - <unresolved>
  10: 0x7ff65065c311 - <unresolved>
  11: 0x7ff64ea0acf7 - <unresolved>
  12: 0x7ff6507fbe8c - <unresolved>
  13: 0x7ffb66867034 - BaseThreadInitThunk
  14: 0x7ffb66ec2651 - RtlUserThreadStart'''
```

**Comment by Connoropolous** [comment]
Oh interesting. The issue is actually the same as #160 reported on Linux. We've been working on that issue, and I expect our proposed fix to address this as well 👍

**Comment by TechSupport26** [comment]
I think I have found a temporary fix for windows
I suppose you can also just run it twice

https://user-images.githubusercontent.com/65631811/189583695-3c7e8667-ebdf-4c0d-81de-e3e88f0d6d0e.mp4

Create a bat file and change the user location for the lair-keystore (in quotation marks)

taskkill /f /IM explorer.exe
start explorer.exe
cd C:\Users\"~~~~~"\AppData\Local\Programs\acorn\resources\app.asar.unpacked\binaries
start lair-keystore
cd C:\Users\zephd\Desktop
start Acorn
timeout 5
start Acorn

**Comment by Connoropolous** [comment]
@TechSupport26 
I saw your reaction on the brand new 1.1.1 release. Can you let us know if this issue is resolved for you?

**Comment by TechSupport26** [comment]
@Connoropolous 
Works perfectly from what I can see and loaded very quickly.
Thanks again 😄
