### ISSUE TITLE
Ticket not able to be marked as Achieved with misleading icon

### ISSUE THREAD

**Issue by shanedeeodonnell** [lightningrodlabs/acorn#159]
Version 1.1.0-alpha (1.1.0-alpha)

@Connoropolous Currently happening on the REA Playspace project 

I can't change the outcome from Not Achieved but its icon is that of one that has been achieved. The ticket colour is that of one that is Not Achieved.
 
<img width="794" alt="Screen Shot 2022-09-08 at 3 49 05 PM" src="https://user-images.githubusercontent.com/16504076/189212886-7587a055-4740-4ac0-9cae-0b2ba17a0b48.png">

**Comment by Connoropolous** [comment]
True, I see that. I think @pegahvaezi observed the same yesterday. It is just incorrectly marked as Not Achieved in the "Expanded View"

**Comment by Connoropolous** [comment]
Thankfully it's a UI fix, so it's easily remediated without any data migration

**Comment by Connoropolous** [comment]
I've just figured this one out, so this will be resolved in the upcoming release. It also affects the color of the card in the Map View
