### ISSUE TITLE
add keyboard cursor navigation

### ISSUE THREAD

**Issue by samcooley** [lightningrodlabs/acorn#16]
Imagine it could be useful in a number of places, and one where I instinctively tried to use keyboard cursor navigation was right and left arrows to flip through intro slides: web/src/components/IntroScreen/IntroScreen.js

**Comment by samcooley** [comment]
Is it as simple (for the example case) as adding an IntroScreen/actions.js?
Or does it need more like https://stackoverflow.com/questions/42036865/react-how-to-navigate-through-list-by-arrow-keys ?

**Comment by Connoropolous** [comment]
adding the feature request label :) it will get triaged

**Comment by Connoropolous** [comment]
I might also add an "accessibility" label because this would be part of a sweep of the whole system for accessibility

**Comment by pegahvaezi** [comment]
The intro screens are now freshly updated in the 1.1.0-alpha release. You can now navigate through the intro slides using right and left arrow keys.
