### ISSUE TITLE
Card description removed when switching scope

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#164]
1. Write some text in the card's description.
2. While still editing the description change the card's scope.
3. Text is removed.

Thanks

https://user-images.githubusercontent.com/65631811/189782180-e32d7870-94b0-4ab6-953d-e25f2066e85d.mp4

**Comment by TechSupport26** [comment]
Is it possible to have Acorn keep the zoom size the same when you go in/out or refresh a project as each time I will scroll out to 

I don't know if this is intended but I like using the mouse buttons to go back and forth from the main page to the previous project. I assume that is from the Acorn window having some of the same features as a browser window. A cool feature.

**Comment by Connoropolous** [comment]
This is fixed in v2.0.0, out now.
