### ISSUE TITLE
UI issue with sorting projects while a project is queued for sync

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#165]
Just a small UI issue with sorting projects

![image](https://user-images.githubusercontent.com/65631811/189783103-ec8ed01b-9962-45db-9203-7372848ed5ec.png)
![image](https://user-images.githubusercontent.com/65631811/189783187-c0f4256d-cfc9-4b28-becb-fe70ccc0473c.png)

**Comment by pegahvaezi** [comment]
yes, that's a bug we've caught as well, which will be fixed for the next release!

**Comment by TechSupport26** [comment]
All fixed with v1.1.1-Alpha
Thanks
