### ISSUE TITLE
Weird layout of leafs

### ISSUE THREAD

**Issue by qubist** [lightningrodlabs/acorn#168]
<img width="1419" alt="Screen Shot 2022-09-15 at 9 43 44 AM" src="https://user-images.githubusercontent.com/3607279/190419774-f1eea8b2-9a50-44ae-8c2e-890c2c7cb1c8.png">

We think the two middle leafs there should stick with their siblings

**Comment by Connoropolous** [comment]
true! That'll come under an upcoming scope of work where we actually get ourselves into some of the more nitty gritty parts of the layout algo. Right now it's all (mostly minus a bit) outsourced to dagre library for the tree arranging

**Comment by Connoropolous** [comment]
closed in https://github.com/lightningrodlabs/acorn/releases/tag/v2.1.0-alpha

**Comment by TechSupport26** [comment]
I would just like to add this. I know that it should not happen and when this get's fixed this will no longer be an issue but I thought to share it.

![image](https://user-images.githubusercontent.com/65631811/199152720-1648d53e-b650-4c5d-8fdd-58c92cd43476.png)
