### ISSUE TITLE
The tree resizes and refocuses after I type in a new outcome in a surprising way.  

### ISSUE THREAD

**Issue by zippy** [lightningrodlabs/acorn#169]
After you hit enter and the tree re-flows, the zoom size also changes, I want it to stay the same size!

**Comment by Connoropolous** [comment]
agree! 
I had a feeling that was going to rub

**Comment by Connoropolous** [comment]
@pegahvaezi

**Comment by Connoropolous** [comment]
actually, I'll close this when the next release goes out

**Comment by Connoropolous** [comment]
fixed in v2.1.0-alpha
