### ISSUE TITLE
Implement edit tag feature

### ISSUE THREAD

**Issue by shanedeeodonnell** [lightningrodlabs/acorn#171]
I was attempting to change the colour of the tag after creating it.

<img width="330" alt="Screen Shot 2022-09-18 at 4 33 25 PM" src="https://user-images.githubusercontent.com/16504076/190927176-68dd6ce1-dfed-438c-81da-573a98782d0b.png">
<img width="317" alt="Screen Shot 2022-09-18 at 4 33 30 PM" src="https://user-images.githubusercontent.com/16504076/190927177-378eb01c-4ad4-406c-8444-884af0fd556f.png">

**Comment by Connoropolous** [comment]
ah that's right. In fact, edit tag isn't even a feature yet. oops hehe

**Comment by jakobwinter** [comment]
Yeah, editing tags would be nice

**Comment by Connoropolous** [comment]
your comment prompted us to work on this today! 
it will be out with the next release which should come quite soon.

**Comment by Connoropolous** [comment]
cc @pegahvaezi

**Comment by TechSupport26** [comment]
Thanks for adding this.

Will we be able to delete tags in the future?

**Comment by pegahvaezi** [comment]
yes, deleting tags function is in the roadmap.
