### ISSUE TITLE
acorn v0.5.1 issue on Ubuntu 18.04.5

### ISSUE THREAD

**Issue by HedayatAbedijoo** [lightningrodlabs/acorn#18]
I am receiving this error in the log file.
/lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29' not found

And the `GLIBC_2.29` can not be installed on Ubuntu 18.

**Comment by Connoropolous** [comment]
Just quoting a point made by @ddd-mtl on this issue for later reference: 

> I believe the best approach for Acorn would be to bundle a copy of the glibc with it. Other approach would be to be dependent to an older version of glibc which is more common. Here is an article that explains this kind of issue on linux  https://utopixel.games/en/blog/building-outer-wonders-for-linux/

**Comment by pegahvaezi** [comment]
@HedayatAbedijoo let us know if this issue still persists in the latest release (v1.0.2-alpha).

**Comment by Connoropolous** [comment]
super thanks. closing
