### ISSUE TITLE
Tooltip for outcome statement UI stays visable

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#200]
Tooltip for outcome statement visible when the mouse is no longer over the card until you move the mouse again.
I think this is because the mouse position is not updated so the code does not check if the mouse is over the same part of the canvas.

https://user-images.githubusercontent.com/65631811/199156706-c5441aec-dd63-4b00-b4a7-2ebbd37e95ab.mp4

Thanks :D

**Comment by TechSupport26** [comment]
Also, the outcome connector size is a little small when you zoom in all the way and a little big when zoomed out to 12%, especially for the Small Scope cards. Perhaps they could be separated a little when zoomed out.
![image](https://user-images.githubusercontent.com/65631811/199160866-2549b741-c9b3-419f-b2f1-fbe7783289c5.png)
![image](https://user-images.githubusercontent.com/65631811/199161497-d68d50bb-37aa-404c-8bde-0918b9ec92ee.png)

**Comment by Connoropolous** [comment]
thanks for the feedback, keep it coming! These are some big adjustments and we need feedback :)

**Comment by Connoropolous** [comment]
fixed in the new https://github.com/lightningrodlabs/acorn/releases/tag/v2.1.1-alpha !

**Comment by TechSupport26** [comment]
![image](https://user-images.githubusercontent.com/65631811/199416085-723af796-cc63-46ff-88d0-9d0353dbb6fa.png)
This is in v2.1.1-alpha
You can make it even bigger.

**Comment by TechSupport26** [comment]
You can trick the outcome statement by right-clicking a card and moving the mouse over the outcome statement. Nothing big.
