### ISSUE TITLE
Using the Connect tool makes it hard to change the child's card parent.

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#203]
v2.1.1
When joining cards using the Connect tool it is very hard to change the child's card parent afterward.

https://user-images.githubusercontent.com/65631811/199414517-2257d044-4689-4c52-852a-d86a16a38aa1.mp4

**Comment by pegahvaezi** [comment]
@Connoropolous what do you think could be the relationship between this bug and the multi parent bug @TechSupport26 replicated in a comment on #127 ?

**Comment by TechSupport26** [comment]
This is no longer an issue. 😃
