### ISSUE TITLE
Entrypoints seem to be added multiple times and cannot be unchecked

### ISSUE THREAD

**Issue by matthme** [lightningrodlabs/acorn#207]
When checking the "Entrypoint" checkmark on an outcome, it has been added multiple times (up to 3 times) and I could not uncheck it anymore.
When trying to uncheck I see the following console error twice in a row:
```
Wasm runtime error while working with Ribosome: RuntimeError: WasmError { file: \"/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/holochain-0.0.165/src/core/ribosome/host_fn/delete.rs\", line: 104, error: Host(\"A mandatory record is missing, dht hash: uhCkku9ZRl6Z_lfk2bxFmmToCBH4__XuiLvQL7dcVHhW1iQ90cXFS\") }"
```

**Comment by TechSupport26** [comment]
You can uncheck them sometimes if you refresh the project and open the card but it is a little finicky.

https://user-images.githubusercontent.com/65631811/200092732-19ad689a-0124-40d1-96e5-3cbdfb405bdc.mp4

**Comment by matthme** [comment]
Good to know, thank you :)

**Comment by TechSupport26** [comment]
I don't think this is an issue now with v4.0.0-alpha.

**Comment by TechSupport26** [comment]
@Connoropolous 
I believe that this issue and #235 can be closed now as it is not present in newer versions.

**Comment by pegahvaezi** [comment]
yes this is fixed in the newer versions
