### ISSUE TITLE
Acorn had problems starting and wont create projects

### ISSUE THREAD

**Issue by zaunders** [lightningrodlabs/acorn#218]
On windows 10, application would'nt start, installed about a week ago. Closed the app and tried again. Then it started. But when I try to create a project it will promt me for name and image but I never get to the project window.

**Comment by zaunders** [comment]
error messages
![error](https://user-images.githubusercontent.com/6172443/205947318-a75f2ab8-7337-404e-af8a-da9d7e1a52e1.png)

**Comment by Connoropolous** [comment]
hey @zaunders , thanks for logging. 

None of the visible errors are problematic ones, nor related to your issue. 

It looks like you have a number of projects created. What is the one that is in the 'project queued for sync'? You can see what it's phrase was by clicking 'Show details'. Is it a project secret you recognize and tried to join, or is it perhaps the one that failed to fully create?

**Comment by pegahvaezi** [comment]
Hi @zaunders, what version of Acorn have you installed? Can you try installing the latest release (v3.0.0-alpha) to see if the issue persists or not?
