### ISSUE TITLE
Feature: Outcome cards can have different colors to associate them without direct inheritance

### ISSUE THREAD

**Issue by snowshiva** [lightningrodlabs/acorn#236]
I want to include outcomes that may relate to different functional groupings, without it having to do with hierarchy.  Background color would be an easy way.

**Comment by Connoropolous** [comment]
Thanks for your feedback and opening a feature idea! 

Perhaps you've already considered this, but I should just check, have you considered using tags to accomplish these functional groupings?

**Comment by pegahvaezi** [comment]
Hi @snowshiva can you let us know if you were able to achieve the same goal with the coloured tags?

**Comment by pegahvaezi** [comment]
closing this thread since it's been inactive. @snowshiva please let us know if you have any updates related to this.
