### ISSUE TITLE
Persistent re-ordering of Outcomes, that would affect list views and map view

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#239]
_Originally posted by @pegahvaezi in https://github.com/lightningrodlabs/acorn/issues/195#issuecomment-1289849260_

**Comment by Connoropolous** [comment]
@zippy this is the one to track, for one of your main feature requests

**Comment by Connoropolous** [comment]
@zippy I had a question for you... would you also like to be able to re-order the top-most-level Outcomes?

**Comment by zippy** [comment]
Absolutely!

**Comment by pegahvaezi** [comment]
@Connoropolous is this the feature we added for release v9.3.1-alpha (re-ordering of siblings by holding shift key and right/left arrows)?

**Comment by Connoropolous** [comment]
the title of the issue also mentions 'list view'. The sorting of Outcomes at this time is not reflected in list view, so not quite, at least per the title.

**Comment by Connoropolous** [comment]
I also can't recall off the top of my head if we added the ability for the top-most level of Outcomes in a project to be sorted, which is proposed in this thread

**Comment by Connoropolous** [comment]
I just completed the reflection of the sorting in the Table View
