### ISSUE TITLE
Option for density selection in the map view

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#244]
Similar to discord's density option between messages could this be implemented in acorn so you can fit more cards on the screen or just have less space between them and have more space if you want less density.

This does not have to be restricted to just the map but I thought it may be a good place to start.

Is this viable or would it be more practical to leave the card spacing as it is and have more space between for those who may want that?

**Comment by TechSupport26** [comment]
Should I close this as now we have Minimum Height and Constrained Width?

**Comment by Connoropolous** [comment]
yeah sure :)
