### ISSUE TITLE
All projects lost after cancelling sync

### ISSUE THREAD

**Issue by matthme** [lightningrodlabs/acorn#248]
This happened on Ubuntu 22.04. I had 5 Projects already up and running in Acorn 4.0.0 when I tried to join another one. It got stuck in synching for a pretty long time although I know another peer was online (it was the laptop right next to me). Then at some point I cancelled the synching and when I reopened acorn next time all projects where gone and they seem to be gone "for good". I assume the data is still there but they simply won't show up on the start page.

When I run it in the terminal, here's what I see:
```
holochain > Looking for passphrase piped to stdin
holochain > Found passphrase, continuing...
holochain > 1
holochain > # lair-keystore connection_url # unix:///home/matthias/.config/acorn/keystore-3/socket?k=3hQiIiZ8wiYr1k6BfQCrucA7IezxH1hPzN5oGHe7QQs #
holochain > # lair-keystore running #
holochain stderr err > Jan 29 22:03:57.690 ERROR holochain::core::queue_consumer: err=SysValidationError(CascadeError(NetworkError(OtherKitsuneP2pError(KitsuneError(KitsuneError(Other(OtherError("rpc_multi failed to get results"))))))))

an unhandled error occurred: Error: Jan 29 22:03:57.690 ERROR holochain::core::queue_consumer: err=SysValidationError(CascadeError(NetworkError(OtherKitsuneP2pError(KitsuneError(KitsuneError(Other(OtherError("rpc_multi failed to get results"))))))))

    at Socket.<anonymous> (/tmp/.mount_Acorn-obj5uZ/resources/app.asar/node_modules/@lightningrodlabs/electron-holochain/dist/src/holochain.js:119:33)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
holochain > 
holochain > ###HOLOCHAIN_SETUP###
holochain > ###ADMIN_PORT:1235###
holochain > ###HOLOCHAIN_SETUP_END###
holochain > DATASTORE_PATH: /home/matthias/.config/acorn/databases-6
holochain > KEYSTORE_PATH: Some("/home/matthias/.config/acorn/keystore-3")
holochain > NETWORK_SEED: None
holochain > Recognized a keypair, using that...
holochain > An existing configuration and identity was found, using that.
holochain >      APP_WS_PORT: 8889
holochain > INSTALLED_APP_ID: acorn-project-331328-uid-[secret-UID]
holochain > HOLOCHAIN_RUNNER_IS_READY
holochain > 7
received checkForMigrationData
^Cholochain > ctrlc got shutdown signal
holochain > successfully sent shutdown signal to embedded-holochain-runner
Killing holochain sub processes...
waiting...
```

**Comment by TechSupport26** [comment]
I am just wondering if you can see the projects dashboard (Homepage). If you can you could try to join your projects by putting the secret code in again. When I did they came up but disappear when you go into the project so I had to put them in again. You can have a look at the comment I made in #243

**Comment by matthme** [comment]
Yes I was thinking about this but didn't have the energy anymore to play around with different things and I wouldn't have remebered the secret words anyway apart from those that I could have looked up somewhere in a chat.

However I did some moving around of the `~/.config/acorn` folder and tried whether things work when starting from scratch (and they seemed to work as far as the little testing goes that I did). Now when I switched back to using the old `~/.config/acorn` folder which I kept a backup of, I suddenly saw that project again that was stuck in queueing for sync and which I previously cancelled and it was again trying to sync but no other projects visible and there where 4 of those errors in the browser console:
```
"Wasm runtime error while working with Ribosome: RuntimeError: WasmError { file: "/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/holochain-0.1.0-beta-rc.1/src/core/ribosome/host_fn/get_links.rs", line: 58, error: Host("rpc_multi failed to get results") }"
```
So probably one for each of the 4 projects that I had.
When I then cancelled that prject that was still queued in sync, all the projects reappeared again!

**Comment by pegahvaezi** [comment]
@matthme is this issue still happening in v9.3.1-alpha?

**Comment by matthme** [comment]
I actually can't tell for sure. I have in the meantime a bunch of acorn backup directories but in none of them I'm able to open those projects with acorn 9.4.1. So either I have deleted that acorn folder at some point or the issue is still there.

**Comment by matthme** [comment]
Okay, I can actually tell now that the issue is still there because when running the AppImage via the command line the UUIDs are "leaked" as they seem to be part of the installed app id in plain text (which I think is its own issue) like this:
```
holochain > INSTALLED_APP_ID: acorn-project-331328-uid-[secret words here]
```
 so I know now that I was trying to access the same projects but they still don't show up in acorn 9.4.1.

**Comment by Connoropolous** [comment]
i dont quite understand the status here. is it important to regain access to those projects? if so, I can try to help do a full assessment of whether that is possible.

**Comment by matthme** [comment]
> is it important to regain access to those projects

No it's not important to get access again in my case. I was just investigating whether the issue is still there in 9.4.1. since I've been asked.

**Comment by Connoropolous** [comment]
I see I see. Ok. Im going to count this as closed since migrating directly from v4 to v9 isnt in our sights as a migration pathway to be concerned with.

**Comment by matthme** [comment]
Just to be clear this is not really a migration issue. The projects got lost in v4 and all I said is that they remain lost in v9. It's not something that occurred during the process of upgrading.
But I don't know how discovery of existing projects in the conductor works so that may have changed between v4 to v9 also. Whether it's worth keeping the issue open is another question...

**Comment by Connoropolous** [comment]
I see. unless the problem still existed in v9 I would close it anyway, as we're not at the point where we do patch fixes on old versions.

**Comment by Connoropolous** [comment]
and by 'problem still existed' I mean the original problem
