### ISSUE TITLE
Windows: Starting acorn fails after it has been closed for the first time.

### ISSUE THREAD

**Issue by matthme** [lightningrodlabs/acorn#249]
I'm not sure whether I'm just trying to open Acorn wrongly on Windows but here's what happens:

1. I installed Acorn on a Windows laptop and created a project.
2. I closed Acorn.
3. Whenever I try to reopen it since then it just gets stuck at the endless splashscreen.

When I open it via Powershell I see the following error and a fatal panic:

```
ERROR holochain_runner::embedded_runner: Conductor returned an error while using a ConductorApi: AppAlreadyInstalled("main-app")
```

Fatal panic report:
```
name = 'holochain-runner'
operating_system = 'windows'
crate_version = '0.5.0'
explanation = '''
Panic occurred in file 'src\embedded_runner.rs' at line 115
'''
cause = 'explicit panic'
method = 'Panic'
backtrace = '''

   0: 0x7ff6b319ed6f - <unresolved>
   1: 0x7ff6b31a1040 - <unresolved>
   2: 0x7ff6b33bd9f5 - <unresolved>
   3: 0x7ff6b33bdaec - <unresolved>
   4: 0x7ff6b148ad5b - <unresolved>
   5: 0x7ff6b12ad772 - <unresolved>
   6: 0x7ff6b0f4918c - <unresolved>
   7: 0x7ff6b2dc80df - <unresolved>
   8: 0x7ff6b2dc7653 - <unresolved>
   9: 0x7ff6b2db5da6 - <unresolved>
  10: 0x7ff6b2dc704f - <unresolved>
  11: 0x7ff6b2dadad4 - <unresolved>
  12: 0x7ff6b2d9e16a - <unresolved>
  13: 0x7ff6b2dbd810 - <unresolved>
  14: 0x7ff6b2dcd654 - <unresolved>
  15: 0x7ff6b2db0178 - <unresolved>
  16: 0x7ff6b2dac2b8 - <unresolved>
  17: 0x7ff6b31ac85c - <unresolved>
  18: 0x7ff9833a74b4 - BaseThreadInitThunk
  19: 0x7ff9836626a1 - RtlUserThreadStart'''
  ```
  
I think fatal errors like this should ideally be detected and somehow made visible in the UI instead of getting stuck at the endless splashscreen.

**Comment by matthme** [comment]
Even after uninstalling and reinstalling this behavior remains so it seems I can't use Acorn anymore on that laptop.

**Comment by matthme** [comment]
Same happens with acorn 3.0.0-alpha

**Comment by pegahvaezi** [comment]
@matthme does this issue still happen with v9.3.1-alpha?

**Comment by matthme** [comment]
I had access today to that PC again and tried to open acorn. It opened fine today with acorn 4.0.0 but (before attempting to open the project that I had created on that PC) it prompted me to update to 9.3.1. I clicked on "Update", then it told me that automatically updating is only supported on macOS. So I manually downloaded it from github and installed it (the .exe file does not seem to be code signed by the way, I'm not sure that's known).
Upon re-opening it said something along the lines of "synching/waiting for peer" although this project was actually created on this very machine in the first place so there would be no need to synch anything. Then When I refreshed the page, the project disappeared completely and it remained disappeared after restarting acorn 9.3.1.
I then tried to reinstall acorn 4.0.0 but now when I open acorn 4.0.0 I cannot open the project anymore either as it says "Update to access". So I'm basically locked out of that project again.

**Comment by TechSupport26** [comment]
> I then tried to reinstall acorn 4.0.0 but now when I open acorn 4.0.0 I cannot open the project anymore either as it says "Update to access". So I'm basically locked out of that project again.

There is a hack way (Unofficially I suppose) to get access to projects in older versions. Check this out. https://github.com/lightningrodlabs/acorn/issues/282#issue-1699239883

I don't know if this will create issues later on but I would definitely export the project.

**Comment by Connoropolous** [comment]
hey @matthme 

- we know abt Windows not codesigning. weve never ventured to set that up yet, but maybe we will bump it up
- the 'update to access' issue we've solved in subsequent versions of Acorn

do you need access to that project? i can write up how to override that block

**Comment by matthme** [comment]
> the 'update to access' issue we've solved in subsequent versions of Acorn

Cool :)

> we know abt Windows not codesigning. weve never ventured to set that up yet

Okay, yes Windows code signing is a pain so I don't blame you ;) I just recently uploaded an unsigned executable by accident myself so I thought it's worth mentioning anyway

**Comment by Connoropolous** [comment]
I've opened an issue for windows codesigning. I think I'll do it soon.
 #340

**Comment by Connoropolous** [comment]
I'm closing this issue though.
