### ISSUE TITLE
Profile creation page visual limitation

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#259]
v4.0.0-alpha When you get the profile setup page on Debian and don't provide enough space for the profile_edit_form the top and bottom get cut off. For me I was always able to access the Ready To Start button but I could not see the text unless I had a  height of more than 803px. (The window did jump to this point when I got close to it)
Windows also has this UI bug.

![image](https://user-images.githubusercontent.com/65631811/225441733-3765d49a-2a0d-4775-bbeb-3a26baca8163.png)

**Comment by Connoropolous** [comment]
just fixed this in v6!
