### ISSUE TITLE
upgrade from a higher version to a lower version issue

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#263]
Folks affected that we know of so far:
@maackle @zippy Abe

There is an issue where it is recommending to upgrade, even though the 'new version' is an older version. Then, if someone has migrated a project, it triggers the rest of the project collaborators to feel (but not actually "be") locked out of their projects.

**Comment by Connoropolous** [comment]
related code:

https://github.com/lightningrodlabs/acorn/blob/main/web/src/hooks/useVersionChecker.ts

https://github.com/lightningrodlabs/acorn/blob/105603e81487806d76af5c472c8250df4095e47e/web/src/routes/Dashboard/DashboardListProject.tsx#L75-L80

**Comment by Connoropolous** [comment]
if we commented out that code and cut a new version and release, you all would have no trouble accessing your projects.

**Comment by maackle** [comment]
That's good to hear.

**Comment by maackle** [comment]
Yay, as a workaround, I can use Developer Tools to manually delete this div from the DOM, and then I can access my project

**Comment by maackle** [comment]
Wondering if there's any plan to release a fix? It's pretty problematic for anyone who doesn't know the workaround, and it's a bit of a deterrent even for me, self proclaimed #1 Acorn fan (because I am lazy).

**Comment by Connoropolous** [comment]
Yes, we are bringing on another person to our team this week who will help us revitalize Acorn and address the backlog, and we can put this right up near the top!
