### ISSUE TITLE
Unable to access project due to v5.0.0-alpha deployment

### ISSUE THREAD

**Issue by dillonfagan** [lightningrodlabs/acorn#273]
Since the fifth alpha was deployed, I've been unable to access my existing project. Attempting to update fails, presumably because there are no builds available. Was the deployment of v5 intentional?

<img width="837" alt="Screenshot 2023-04-29 at 11 50 18 AM" src="https://user-images.githubusercontent.com/5107025/235311589-8b005cad-781c-4494-a47a-a083d8034b64.png">

**Comment by Connoropolous** [comment]
Hi there,

Apologies, we have had some difficulties performing this round of releases, and are working through both the release process and the update process. Thanks for logging the issue. 

Did you get into the state you're in after attempting to update?

**Comment by Connoropolous** [comment]
We are trying again

**Comment by Connoropolous** [comment]
We will get this fixed and get you access again!

**Comment by dillonfagan** [comment]
Hi @Connoropolous, thanks for getting back to me! When I opened the app this morning, it had the banner to update. I clicked Update and it became stuck at 50%.

**Comment by Connoropolous** [comment]
Hi the release 5 finally worked. I would recommend this…
Download the new release manually and launch it

**Comment by dillonfagan** [comment]
I downloaded and ran, but it's stuck on the initial "Welcome to acorn..." window. I've tried deleting the acorn folder from ~/Library/Application Support/, but this hasn't fixed it.

**Comment by Connoropolous** [comment]
@dillonfagan 
we've had some larger issues with this version, despite our doing QA before it went out. 
Let's see if we can get it resolved. 

Do you still have your `acorn` folder in your trash?

**Comment by dillonfagan** [comment]
@Connoropolous Hey Connor, no worries -- I know some bugs can even get past QA sometimes. I still have the folder, yes.

**Comment by Connoropolous** [comment]
that's good. so, we have fixed one more error since my last message, so we are releasing. 

You can do this step now, and the second step later: 
Open `Activity Monitor` on your computer. Search in the CPU tab for the process called `holochain-runner`. Click on 'x' and select Force Quit, and confirm. 

Once version 5.0.2 comes out, download that one and run it. Depending on whether you do or don't need your old data back, replace the `acorn` folder where it was.

**Comment by dillonfagan** [comment]
Thanks! I'll let you know how it works once I have 5.0.2.

**Comment by TechSupport26** [comment]
I am now having a similar issue with v5.0.2 as well.

![image](https://user-images.githubusercontent.com/65631811/235547242-67310536-9fb9-42f3-96be-d9add8415380.png)

**Comment by Connoropolous** [comment]
can you open a new issue @TechSupport26 and provide the full set of details surrounding your issue?

**Comment by dillonfagan** [comment]
@Connoropolous I got 5.0.2 working, but it wasn't able to load my old project. It's not the end of the world if it's gone, but was wondering if there's something in the acorn directory I could pull out to salvage it.

From running `ls` inside `acorn`:

Cache				
Preferences
Code Cache			
Session Storage
Cookies				
TransportSecurity
Cookies-journal		
blob_storage
GPUCache			
databases-8
Local Storage			
keystore-4
Network Persistent State

**Comment by Connoropolous** [comment]
what does your dashboard look like? there are 0 projects?

**Comment by dillonfagan** [comment]
No projects. When I launched, I had to set up a new user. I may have run v5, then v4, then v5 again when I was initially having problems. Like I said, no worries if the project isn't recoverable.

**Comment by Connoropolous** [comment]
Ok. Based on the info you've given, I can't see a way to recover your project. Apologies, and still I'm glad it was low stakes!

**Comment by dillonfagan** [comment]
No worries and thank you again for the help. Acorn is still an awesome app!
