### ISSUE TITLE
Acorn does not stop running

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#274]
I am running Debian 12
v-5.0.0-alpha

Acorn does not complete stop when I close it so when I try to open it again Acorn won't load. See the below output.

I can kill the process my self and then it will run again.

./Acorn-5.0.0-alpha.AppImage 
holochain > Looking for passphrase piped to stdin
holochain > Found passphrase, continuing...
holochain > 1
holochain > # lair-keystore connection_url # unix:///home/zeph/.config/acorn/keystore-4/socket?k=caNYTx4zbT9fw9UPrQsSipJrJEeZ_fajLZ2hb_DNu3c #
holochain > # lair-keystore running #
holochain stderr err > FATAL PANIC PanicInfo {
    payload: Any { .. },
    message: Some(
        Could not initialize Conductor from configuration: InterfaceError(WebsocketError(Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))),
    ),
    location: Location {
        file: "src/embedded_runner.rs",
        line: 135,
        col: 10,
    },
    can_unwind: true,
}

an unhandled error occurred: Error: FATAL PANIC PanicInfo {
    payload: Any { .. },
    message: Some(
        Could not initialize Conductor from configuration: InterfaceError(WebsocketError(Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))),
    ),
    location: Location {
        file: "src/embedded_runner.rs",
        line: 135,
        col: 10,
    },
    can_unwind: true,
}

    at Socket.<anonymous> (/tmp/.mount_Acorn-lNRW71/resources/app.asar/node_modules/@lightningrodlabs/electron-holochain/dist/src/holochain.js:119:33)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
holochain stderr err > Well, this is embarrassing.

holochain-runner had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-2b66b39f-871c-43f1-a9af-a63065f42d75.toml". Submit an issue or email with the subject of "holochain-runner Crash Report" and include the report as an attachment.

- Authors: Connor Turland <connor@sprillow.com>, Wesley Finck <wesleyfinck@gmail.com>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!

an unhandled error occurred: Error: Well, this is embarrassing.

holochain-runner had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-2b66b39f-871c-43f1-a9af-a63065f42d75.toml". Submit an issue or email with the subject of "holochain-runner Crash Report" and include the report as an attachment.

- Authors: Connor Turland <connor@sprillow.com>, Wesley Finck <wesleyfinck@gmail.com>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!

    at Socket.<anonymous> (/tmp/.mount_Acorn-lNRW71/resources/app.asar/node_modules/@lightningrodlabs/electron-holochain/dist/src/holochain.js:119:33)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
holochain > 
holochain-runner closed with code:  101

### Here is the report

name = 'holochain-runner'
operating_system = 'unix:Debian'
crate_version = '0.6.0'
explanation = '''
Panic occurred in file 'src/embedded_runner.rs' at line 135
'''
cause = 'Could not initialize Conductor from configuration: InterfaceError(WebsocketError(Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" })))'
method = 'Panic'
backtrace = '''

   0: 0x55feef2bf843 - <unresolved>
   1: 0x55feef2bfb03 - <unresolved>
   2: 0x55feef770625 - <unresolved>
   3: 0x55feef377e95 - <unresolved>
   4: 0x55feef50017d - <unresolved>
   5: 0x55feef50bd3c - <unresolved>
   6: 0x55feef65d1cc - <unresolved>
   7: 0x55feef832fb3 - <unresolved>
   8: 0x55feef5ffe69 - <unresolved>
   9: 0x55fef1504c7b - <unresolved>
  10: 0x55feef65d835 - <unresolved>
  11: 0x7f139f8fa18a - <unresolved>
  12: 0x7f139f8fa245 - __libc_start_main
  13: 0x55feef2c0155 - <unresolved>
  14:        0x0 - <unresolved>'''

### Computer Specs
Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.2
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-6-amd64 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-7500U CPU @ 2.70GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620
Manufacturer: Dell Inc.
Product Name: XPS 13 9360

Thanks.

**Comment by Connoropolous** [comment]
If you ran 
‘lsof -nP -iTCP -sTCP:LISTEN | grep 1234’

You can find the ID of the orphaned Holochain process. It needs to shut down before Acorn will start

**Comment by Connoropolous** [comment]
Sorry, I didn't read your full message. You pointed out the same thing I pointed out. 
I've taken note, and we will see if we can fix that asap!

**Comment by TechSupport26** [comment]
Resolved with Version v5.0.2
