### ISSUE TITLE
Linking parent to itself crashes ACORN

### ISSUE THREAD

**Issue by adamth0mps0n** [lightningrodlabs/acorn#281]
I accidentally dragged the parent link in a loop and it crashed badly: 
Seems that the function is calling itself repeatedly without terminating. 

Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at computeAchievementStatus (file:///tmp/.mount_Acorn-z2CeBa/resources/app.asar.unpacked/web/app.js:94067:34)
    at getOutcome (file:///tmp/.mount_Acorn-z2CeBa/resources/app.asar.unpacked/web/app.js:96989:101)
    at file:///tmp/.mount_Acorn-z2CeBa/resources/app.asar.unpacked/web/app.js:96987:34
    at Array.map (<anonymous>)
    at getOutcome (file:///tmp/.mount_Acorn-z2CeBa/resources/app.asar.unpacked/web/app.js:96987:14)
    at file:///tmp/.mount_Acorn-z2CeBa/resources/app.asar.unpacked/web/app.js:96987:34
    at Array.map (<anonymous>)
    at getOutcome (file:///tmp/.mount_Acorn-z2CeBa/resources/app.asar.unpacked/web/app.js:96987:14)
    at file:///tmp/.mount_Acorn-z2CeBa/resources/app.asar.unpacked/web/app.js:96987:34
    at Array.map (<anonymous>)

**Comment by Connoropolous** [comment]
owch. 
Thanks for logging. We'll push a fix.

cc @kbonnici

**Comment by kbonnici** [comment]
@adamth0mps0n would you be able to provide a screen capture of how you managed to do this? You shouldn't be able to link a card to itself, and when I attempted to do so I didn't get any unexpected behaviour.

**Comment by TechSupport26** [comment]
What appears to be happening is that the blue outcome connector icon does not appear but the connection line still jumps to where the outcome connector would be.

This also happens in Windows 10 but instead of crashing all the cards in the project just disappear.

https://user-images.githubusercontent.com/65631811/236953716-d3d418eb-087e-4bdb-ae64-e3a4be3074b3.mp4

Linux Below

**Comment by adamth0mps0n** [comment]
https://user-images.githubusercontent.com/49579958/236954195-0c77b6a8-5140-413f-a5e2-c5d0aa50149d.mp4

Here's a video of the error --> Debian 12 with KDE Wayland

**Comment by kbonnici** [comment]
@TechSupport26 @adamth0mps0n i have implemented a fix which will prevent people from doing this in the future, but the fix does not delete those particular illegal connections which you made. Therefore, your projects which have those illegal connections will continue to be bugged and will crash Acorn. 

My question to you both is this: did you encounter this bug on any projects which you actually use? If not, then we will push the fix and those toy projects which you encountered the bug on will remain bugged. If you actually *need* one of the projects in which you encountered the bug, then we will guide you through an admittedly ugly manual fix, but your projects will be fixed.

**Comment by kbonnici** [comment]
That's what i was afraid of. If the connection was propagated to the other members of the project then the entire project is essentially broken. We will be able to fix it, but it involves directly modifying the JSON data of the project. @Connoropolous will have a better idea of how do to that than me, but we will push the fix tomorrow.

Does another member of the project have a non-broken copy that they can export and allow the others to join for the time being?

**Comment by TechSupport26** [comment]
Perhaps. @adamth0mps0n will have to ask when he gets back.

Any idea where the json file would be?

**Comment by Connoropolous** [comment]
@TechSupport26 and @adamth0mps0n 
we've done a new release of Acorn, v6.0.1-alpha.

Can you tell me about which version of Acorn you're currently using, and on which platform?

**Comment by Connoropolous** [comment]
I'd like to assist you in upgrading if I can

**Comment by TechSupport26** [comment]
Hi Connor. We have not moved versions yet. I have been trying to upgrade on a vm on both Linux and windows. that I have and was not successful. I have been meaning to make an issue about it.

We are still on version 5.0.2-alpha. We are using Linux and Mac OS. I will let Adam know and get him to message you as he and the other member are leading the project.

Thanks.

**Comment by Connoropolous** [comment]
we had a flop with version 6.0.0, that we remediated in version 6.0.1
have you tried that?

**Comment by TechSupport26** [comment]
I have not been able to just yet. But on windows I get an error. Will send it when I get home.

**Comment by TechSupport26** [comment]
I ran a fresh install on Windows and Debian and have not run into any errors when switching versions. Don't know how but it is fixed.

Just one hiccup. This is the same error as the one I got on windows.
![image](https://github.com/lightningrodlabs/acorn/assets/65631811/b5722404-246a-42d6-963c-56d9a5a64138)

What do you think.

**Comment by Connoropolous** [comment]
If you are on Linux, then go to ~/.config/acornIn that folder you will find a file called data-migration-for-integrity-version-8 or maybe -7 . Move that file out of that folder but don’t delete it. Restart Acorn. You won’t be routed to the migration screen anymore. Again, just in case we need it to recover any data for you, don’t delete that file, just move it out of the folder. On Jun 12, 2023, at 6:22 PM, TechSupport26 ***@***.***> wrote:﻿
I ran a fresh install on Windows and Debian and have not run into any errors when switching versions. Don't know how but it is fixed.
Just one hiccup. This is the same error as the one I got on windows.

What do you think.

**Comment by TechSupport26** [comment]
I tried moving the data-migration-for-integrity-version-8 but only 1 project loaded and none of the cards inside were present. I get the following.
![image](https://github.com/lightningrodlabs/acorn/assets/65631811/4a2548ab-3139-417c-8ddc-a56eae2ccb7f)

**Comment by TechSupport26** [comment]
Trying Version-6.1.0-alpha does not change anything. But I have gone in to the project that loaded before and the cards are present. They just don't show on the map view.

**Comment by Connoropolous** [comment]
Can’t you re-describe to me what is your full ideal outcome right now? Like, do you have projects that need recovering? On Jun 14, 2023, at 5:41 PM, TechSupport26 ***@***.***> wrote:﻿
Trying Version-6.1.0-alpha does not change anything. But I have gone in to the project that loaded before and the cards are present. They just don't show on the map view.

**Comment by TechSupport26** [comment]
The ideal outcome is to move to the latest version and re-share the project, in doing so would recover the project. This could be done as follows.

I am under the assumption that we have one unbroken copy that we can re-share.
This means that Adam and myself can delete the acorn folder, re-import our projects to the latest version and get the secret phrase to the last project.

**Comment by Connoropolous** [comment]
yes, by the sounds of it, what I would suggest is deleting only 
‘databases-9’ and ‘keystore-5’ in the acorn folder. 

I think something went wrong during your migration and that’s bricked your current state

**Comment by Connoropolous** [comment]
I will put “factory reset this version” into the backlog so this can be done with one click on the future

**Comment by TechSupport26** [comment]
In regards to this issue. In version 6.1.0-alpha I can now create loops again causing Acorn to crash.
This only happens in certain circumstances.

1. Create 4 cards and join them together so they are in a column. A, B, C, D
2. Create a child card (E) from the top card (A) and link it to the 3rd card (C) in the column. There should be one card left at the bottom (D).
3. Connect  the (D) card with the bottom connector and connect it to the (E) card. (It should be the only option available)
4. Acorn will crash.

`Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at file:///tmp/.mount_Acorn-5al2WJ/resources/app.asar.unpacked/web/app.js:94719:21
    at Array.filter (<anonymous>)
    at getOutcome (file:///tmp/.mount_Acorn-5al2WJ/resources/app.asar.unpacked/web/app.js:94719:14)
    at file:///tmp/.mount_Acorn-5al2WJ/resources/app.asar.unpacked/web/app.js:94721:34
    at Array.map (<anonymous>)
    at getOutcome (file:///tmp/.mount_Acorn-5al2WJ/resources/app.asar.unpacked/web/app.js:94721:14)
    at file:///tmp/.mount_Acorn-5al2WJ/resources/app.asar.unpacked/web/app.js:94721:34
    at Array.map (<anonymous>)
    at getOutcome (file:///tmp/.mount_Acorn-5al2WJ/resources/app.asar.unpacked/web/app.js:94721:14)
    at file:///tmp/.mount_Acorn-5al2WJ/resources/app.asar.unpacked/web/app.js:94721:34`

**Comment by TechSupport26** [comment]
> In regards to this issue. In version 6.1.0-alpha I can now create loops again causing Acorn to crash.
This only happens in certain circumstances. From what I have found.

This is still present in v7.1.0

**Comment by pegahvaezi** [comment]
@Connoropolous does this issue still exist in v9.3.1-alpha?

**Comment by Connoropolous** [comment]
Not 100% certain. I suggest attempting to actually reproduce it and find out.

**Comment by TechSupport26** [comment]
Yes. This still occures.

Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at getOutcome (file:///C:/Users/Zeph.Thompson/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103777:24)
    at file:///C:/Users/Zeph.Thompson/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103787:34
    at Array.map (<anonymous>)
    at getOutcome (file:///C:/Users/Zeph.Thompson/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103787:14)
    at file:///C:/Users/Zeph.Thompson/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103787:34
    at Array.map (<anonymous>)
    at getOutcome (file:///C:/Users/Zeph.Thompson/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103787:14)
    at file:///C:/Users/Zeph.Thompson/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103787:34
    at Array.map (<anonymous>)
    at getOutcome (file:///C:/Users/Zeph.Thompson/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103787:14)


https://github.com/lightningrodlabs/acorn/assets/65631811/3a8fe9f4-f25f-47ce-a851-5291e3bcd4ca

**Comment by pegahvaezi** [comment]
@Connoropolous what would the best label for this issue?

**Comment by pegahvaezi** [comment]
@TechSupport26 as of v9.9.0-alpha we are not able to replicate this scenario (as it doesn't allow to connect a child to its parent as a parent). let us know if with the latest version you are still getting the same bug.

**Comment by TechSupport26** [comment]
v9.9.0-alpha
What is shown in the video is not possible anymore but a slightly different option that is mentioned [here](https://github.com/lightningrodlabs/acorn/issues/281#issuecomment-1592375810) (A few comments up) Instead of  connecting to card 5, connect to card 2(E)


Stack trace


Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at Array.filter (<anonymous>)
    at getOutcome (file:///tmp/.mount_Acorn-etdI5o/resources/app.asar.unpacked/web/app.js:103902:14)
    at file:///tmp/.mount_Acorn-etdI5o/resources/app.asar.unpacked/web/app.js:103904:34
    at Array.map (<anonymous>)
    at getOutcome (file:///tmp/.mount_Acorn-etdI5o/resources/app.asar.unpacked/web/app.js:103904:14)
    at file:///tmp/.mount_Acorn-etdI5o/resources/app.asar.unpacked/web/app.js:103904:34
    at Array.map (<anonymous>)
    at getOutcome (file:///tmp/.mount_Acorn-etdI5o/resources/app.asar.unpacked/web/app.js:103904:14)
    at file:///tmp/.mount_Acorn-etdI5o/resources/app.asar.unpacked/web/app.js:103904:34
    at Array.map (<anonymous>)


Inspect element's console ouptut


react-dom.production.min.js:209 RangeError: Maximum call stack size exceeded
    at Array.filter (<anonymous>)
    at getOutcome (outcomesAsGraph.ts:83:8)
    at outcomesAsGraph.ts:85:28
    at Array.map (<anonymous>)
    at getOutcome (outcomesAsGraph.ts:85:8)
    at outcomesAsGraph.ts:85:28
    at Array.map (<anonymous>)
    at getOutcome (outcomesAsGraph.ts:85:8)
    at outcomesAsGraph.ts:85:28
    at Array.map (<anonymous>)
Ci @ react-dom.production.min.js:209
outcomesAsGraph.ts:75 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at getOutcome (outcomesAsGraph.ts:75:22)
    at outcomesAsGraph.ts:85:28
    at Array.map (<anonymous>)
    at getOutcome (outcomesAsGraph.ts:85:8)
    at outcomesAsGraph.ts:85:28
    at Array.map (<anonymous>)
    at getOutcome (outcomesAsGraph.ts:85:8)
    at outcomesAsGraph.ts:85:28
    at Array.map (<anonymous>)
    at getOutcome (outcomesAsGraph.ts:85:8)

Can create video on request.
