### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KJM98** [lightningrodlabs/acorn#285]
Hi there, never added an issue on GitHub, so hopefully I get all the things.

I have been using Acorn and I love it.
I have Acorn version 5.01 and running windows 11, which is completly updated.
I was in a project re-organising when I accidently linked a child to two parents, I have done this before and nothing happened, but here I had block 1 which is parent of block 2 which is parent of block 3 and I linked block 3 to block 2 and 1. And then it crashed. 
I can open Acorn, but if i open that project it crashes.
Sadly I dont have screenshot, only the Acorn has crashed page appears and thats probably not super useful.

Do have this though, I did remove some numbers and name, dont know what can be used for nefarious reasons.

Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at computeAchievementStatus (file:///C:/Users//AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:)
    at getOutcome (file:///C:/Users//AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:)
    at file:///C:/Users//AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:
    at Array.map (<anonymous>)
    at getOutcome (file:///C:/Users//AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:)
    at file:///C:/Users//AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:
    at Array.map (<anonymous>)
    at getOutcome (file:///C:/Users//AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:)
    at file:///C:/Users//AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:
    at Array.map (<anonymous>)

Also I had a backup but when I open it, it just loads forever, never opening.

Hope this is helpful
Keep up the good work, the app is amazing and has helped me sooooooo much
Thank you 
Kind regards

**Comment by Connoropolous** [comment]
Hi, glad to hear youre enjoying Acorn! 

Is the project one that you need to recover? We have a workaround for this if so.

**Comment by Connoropolous** [comment]
Sure. Do you have other projects as well, or is that the only one?

**Comment by KJM98** [comment]
This is the only one

**Comment by Connoropolous** [comment]
we are just working on getting the next release out, and that will allow us to then recover your project

**Comment by Connoropolous** [comment]
it seems like this issue got overlooked. Apologies. Would you still like to recover data? Have you updated to a more recent Acorn?

**Comment by pegahvaezi** [comment]
Hi @KJM98, can you try the newest release (v9.3.1-alpha) and let us know if this issue still persists or not?
