### ISSUE TITLE
Joining a Project Hangs at Queued for Sync in Perpetuity

### ISSUE THREAD

**Issue by MvF-Evangelista** [lightningrodlabs/acorn#288]
After entering the **Project Invitation Secret**, the project is queued for sync and the _acorn_ spins in perpetuity.  Even after doing a _reload_, or _forced reload_, or a reinstall and checking with the project owner to make sure their computer and instance of Acorn is up and running I am unable to join the project.

It should also be noted that when I do quit Acorn and restart it, it hangs at the loading dialog box.  At this point, I have to restart my MacBook Pro (M2) in order to successfully run Acorn to try again.  All that I have described is consistently [without exception] reproducible.

I am on version Version 5.0.2-alpha and the project owner is on 4.x.x-alpha.  I will uninstall and install the 4.x.x version and report back.

**Comment by Connoropolous** [comment]
Hi there. 
Yeah projects will not sync when the first number of the version code is different. 4.x.y will sync with other version 4, but not with a version 5.x.y

**Comment by MvF-Evangelista** [comment]
I am confirming that after downgrading to 4.0.0-alpha I was able to join the project.  :-)

**Comment by Connoropolous** [comment]
Good good. 
I just added a note about this important detail here: https://docs.acorn.software/projects/join-a-project 
(it wasn't there previously)
