### ISSUE TITLE
I can't delete connection

### ISSUE THREAD

**Issue by andersonprante** [lightningrodlabs/acorn#295]
I'm a Linux user, so I recently downloaded the AppImage file.

In the map view, when I select a connection (line highlight) and press delete on the keyboard, nothing happens.

**Comment by Connoropolous** [comment]
@techsupport26 can you reproduce this?

**Comment by TechSupport26** [comment]
Just to be specific. I can delete the connections but I need to press the backspace key. I am assuming that you are referring to that key.

I did have this issue earlier with one connection but after a little while I was able to delete it.

**Comment by andersonprante** [comment]
That's it! I was pressing delete key instead of backspace
