### ISSUE TITLE
Assigning "Assignees" to an Outcome Card: Not All Individuals are Available

### ISSUE THREAD

**Issue by MvF-Evangelista** [lightningrodlabs/acorn#300]
When assigning individuals (Assignees) to an Outcome Card in a particular Acorn project, not all of the the people who are live and running Acorn are available as Assignees - even though they verify live they are running Acorn with the same version that I was running.  Not sure what OS they were running however.

Acorn Version 6.1.0-alpha (6.1.0-alpha)
MacBook Pro
Chip: Apple M2 Max
Memory: 64GB total | 35GB used
macOS: 13.4.1 (22F82)

BTW, I was able to successfully update Acorn from version 4.x to 6.1.x without a problem!  Previous attempts to upgrade at startup failed with previous versions.  Thank you for fixing the spinning wheel of death!  :-)

**Comment by Connoropolous** [comment]
Great news on the update migration!

**Comment by Connoropolous** [comment]
we will investigate the main issue

**Comment by Connoropolous** [comment]
I'm closing this one in favor of #316 which is a duplicate.

**Comment by TechSupport26** [comment]
@MvF-Evangelista Check out my comment in the issue above with a solution when using the latest version.
