### ISSUE TITLE
my profile not an option when selecting assignee 

### ISSUE THREAD

**Issue by weswalla** [lightningrodlabs/acorn#302]
when I go to add an assignee to a card, I don't see my own profile as an option.
![image](https://github.com/lightningrodlabs/acorn/assets/39413655/a5bc0211-5b03-4323-9904-8c296121d01f)

**Comment by weswalla** [comment]
Weird, I updated my profile (by adding an image link) and then I popped up after that:
![image](https://github.com/lightningrodlabs/acorn/assets/39413655/57b31e83-0ad7-40a4-826d-bbabe11fb1bf)

**Comment by Connoropolous** [comment]
similar to #300

**Comment by Connoropolous** [comment]
I'm closing this one in favor of #316 which is a duplicate.

**Comment by TechSupport26** [comment]
@weswalla Check out my comment in the issue mentioned above with a possible solution in the latest version of Acorn.
