### ISSUE TITLE
Acorn 6.1.0 - Alpha Crash

### ISSUE THREAD

**Issue by MvF-Evangelista** [lightningrodlabs/acorn#305]
Environment:

MacBook Pro 
Chip - Apple M2 Max
Memory - 64GB

After creating a new project and inviting another users to collaborate, each of us created a card in the project.  Then I was adding the other person as the Assignee and then clicked on the checkbox for High Priority and Acorn crashed. it crashed.  

After reloading Acorn, and opening up the project that crashed, I clicked my mouse and it immediately crashed.  This was repeatable with the same result (Crash) each time.

If I quit and restart and open a different project, no crash.  But if I open the project that crashed, and click or move my mouse, it crashes.

Here is the stack trace from the crash:

Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.

Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at file:///Applications/Acorn.app/Contents/Resources/app.asar.unpacked/web/app.js:92653:17
    at draw (file:///Applications/Acorn.app/Contents/Resources/app.asar.unpacked/web/app.js:92182:5)
    at file:///Applications/Acorn.app/Contents/Resources/app.asar.unpacked/web/app.js:92621:9
    at draw (file:///Applications/Acorn.app/Contents/Resources/app.asar.unpacked/web/app.js:92182:5)
    at drawAvatar (file:///Applications/Acorn.app/Contents/Resources/app.asar.unpacked/web/app.js:92571:103)
    at file:///Applications/Acorn.app/Contents/Resources/app.asar.unpacked/web/app.js:92698:17
    at Array.forEach (<anonymous>)
    at file:///Applications/Acorn.app/Contents/Resources/app.asar.unpacked/web/app.js:92689:21
    at draw (file:///Applications/Acorn.app/Contents/Resources/app.asar.unpacked/web/app.js:92182:5)
    at drawAssignees (file:///Applications/Acorn.app/Contents/Resources/app.asar.unpacked/web/app.js:92687:9)

**Comment by Connoropolous** [comment]
hey @MvF-Evangelista thanks for logging.
we will see if we can reproduce.

**Comment by Connoropolous** [comment]
it sounds like it was the "clicked on the checkbox for High Priority" that caused it to crash. We will try that.

**Comment by MvF-Evangelista** [comment]
It looks like the crash corrupted the project since every time you open the project and move or click the mouse it crashes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TechSupport26** [comment]
Checkout my explination on issue #299

**Comment by Connoropolous** [comment]
I'm not having any luck reproducing this issue in V7 right now.

**Comment by Connoropolous** [comment]
I am going to close this as I've not been able to reproduce this in V7. Please re-open the issue if it arises again

**Comment by MvF-Evangelista** [comment]
Okay, will do... 7.0.1-alpha seems stable.  I haven't seen the issue and I'm happy with the release so far. :joy:
