### ISSUE TITLE
Export/Import Issue: Importing a project duplicates existing Cards

### ISSUE THREAD

**Issue by MvF-Evangelista** [lightningrodlabs/acorn#307]
Steps to reproduce:

1. Export Acorn project as json
2. Share project with another person
3. They import the project you shared

After the person import your project, any cards that were in the project are duplicated in the shared project.

Version 4.0.0-alpha (4.0.0-alpha)
MacBook Pro M2 | Ubuntu (shared)

**Comment by Connoropolous** [comment]
what would be the expected behaviour?

**Comment by Connoropolous** [comment]
@MvF-Evangelista still wondering about this scenario. What is the real world use case for this scenario?

**Comment by MvF-Evangelista** [comment]
@Connoropolous - well, the use-case is that when you import a project because synch failed or all your peers are off-line.  I don't necessary want to go through the process of deleting duplicate cards and I doubt neither do my peers.  However, maybe I want to choose which duplicate card I want to keep or discard. Just like when you do a merge of data, you should have a choice to keep duplicates or choose the most updated data.  Ideally, I just want the most updated version of the project without duplicate cards/data.
