### ISSUE TITLE
upgrade electron-builder and thus @electron/notarize

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#309]
needed in order to avoid the deprecation of `altool` in favor of `notarytool`

see: https://github.com/electron-userland/electron-builder/commit/00d0dbc2d74fbac3e9ce7a046427c1e1d9a11301

**Comment by pegahvaezi** [comment]
@Connoropolous what would be the label for this issue?

**Comment by Connoropolous** [comment]
'maintenance' maybe. a new label
