### ISSUE TITLE
v7.0.0-alpha: Can't synch Projects

### ISSUE THREAD

**Issue by MvF-Evangelista** [lightningrodlabs/acorn#312]
Installed v7 today and my Acorn peer partner who also installed v7.  He provided me his secret and I am in synch purgatory.   I created a project and he get's an error that says, something to the effect that the secret must be 5 words and in fact it is 5 words.

I am on Mac OS and he is on Ubuntu.

Try synching with me yourself... here is my secret:

**jugular jockstrap audibly paralysis scientist**

Thanks for looking into this!

**Comment by TechSupport26** [comment]
Similar experience for me.
Going between Debian and Windows and it took about 15 minutes to get across.
This was a migrated project adding a new user to it. (hope that made sense).
Thanks,

**Comment by MvF-Evangelista** [comment]
Hey @TechSupport26, do you mind joining my project for a test?

The secret is jugular jockstrap audibly paralysis scientist.

Thanks,

Mark

**Comment by TechSupport26** [comment]
Hey @MvF-Evangelista
Joining the project was very fast.
Not sure why.

**Comment by MvF-Evangelista** [comment]
Hey @TechSupport26 - I see you added a card, but I don't see you otherwise.  Can you have me join one of your projects?

Thanks

**Comment by TechSupport26** [comment]
Yes, I had the same issue. I closed Acorn and reopened it and you were there so try that.

Here is the project secret choking oppressed mushy apostle flashback
Also sent on Acorn.

**Comment by MvF-Evangelista** [comment]
I get an error when I pasted the 5 word secret in as you can see - it says, "Secret must be 5 words".
<img width="578" alt="Screenshot 2023-08-04 at 6 03 53 PM" src="https://github.com/lightningrodlabs/acorn/assets/20306239/666aa287-303d-4403-b710-6693e4d8cdec">

**Comment by TechSupport26** [comment]
Remove 'secret' and you should be golden

**Comment by Connoropolous** [comment]
I am tracking along with this. 
I am having suspicions about how for some reason migrated projects might behave differently than newly created ones

**Comment by MvF-Evangelista** [comment]
@Connoropolous, I am not sharing imported projects.  I created a new project with the secret key: jugular jockstrap audibly paralysis scientist.

**Comment by MvF-Evangelista** [comment]
@TechSupport26, oops!  Removed it but now:
![image](https://github.com/lightningrodlabs/acorn/assets/20306239/d8268a8d-52dd-4e4a-9d30-a956c956ca8d)

**Comment by TechSupport26** [comment]
Interesting. I have not seen that one before.
if you can try closing and opening Acorn, see if that does anything.

**Comment by MvF-Evangelista** [comment]
@TechSupport26 - synching...worked after about 1 minute.

**Comment by TechSupport26** [comment]
Yes, I just realised the same and have made an issue.
I don't see you in the project either. Do you see 3 cards or more/less?

**Comment by MvF-Evangelista** [comment]
4 cards in your project -Acorn v7.0.0-alpha Test Drive. And zero cards in my project - Matt and Mark's Mother of All Projects.  Which is strange.  I had 3 or so cards and they went away.  Not sure if you deleted my cards or not.

**Comment by MvF-Evangelista** [comment]
I finally synched with Matt's project - Thoughts and Ideas.  That literally took all day!

**Comment by Connoropolous** [comment]
by the way, syncing is entirely subject to the online-ness of your peer. So if Matt's laptop is open, and he has Acorn open, you *should* sync. If Matt has Acorn closed, or Matt's laptop lid is closed, etc, then Acorn won't sync

**Comment by MvF-Evangelista** [comment]
Yes, Connor.  But, he told me he had it open at least the first several hours of the day.  Perhaps he loaded Acorn on Windows after Ubuntu failed to sych.  Not sure.  I asked him to do that.  I'll check with him and get back to you.

**Comment by Connoropolous** [comment]
Got it. 👍 just making sure

**Comment by TechSupport26** [comment]
> Not sure if you deleted my cards or not.

I accidentally deleted 1 card but I did add 2 cards.

**Comment by MvF-Evangelista** [comment]
Update:  Matt  left his computer running after I went to bed and he  still haven't been able to sync to my project. He will try to sync to your project with my windows OS later today.

**Comment by Connoropolous** [comment]
In general, the reality is that these types of issues start and end with the holochain version we bundle. 
The best thing that we can do with Acorn is try to surface more information to the user interface about what the internal state of holochain is in a user friendly way so that Holochain itself can be better trouble-shooted (troubleshot?)

**Comment by Connoropolous** [comment]
here is the most basic relevant info to know about it, from a reporting back to holochain perspective: 
holochain conductor: 0.2.1
bootstrap service: https://bootstrap.holo.host
signal service: wss://signal.holo.host

**Comment by pegahvaezi** [comment]
@Connoropolous is this fixed in v9.3.1-alpha or still an issue?

**Comment by Connoropolous** [comment]
as we've no clear single definition of what this issue is, other than 'trouble syncing', and as mentioned here syncing related issues stem from holochain (https://github.com/lightningrodlabs/acorn/issues/312#issuecomment-1672361283) I suggest closing this. The holochain team seems to have their own pretty decent way of tracking and reproducing syncing issues themselves, and so they are working to stabilize it and I expect we'll soon benefit from that in future releases.
