### ISSUE TITLE
Update Acorn with project queued for sync

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#315]
Just so you are aware...
When updating, Acorn is not able to complete the 'Preparing your update' while a project is queued for sync. I get the following in the developer tools.
![image](https://github.com/lightningrodlabs/acorn/assets/65631811/02be7539-7bea-4c76-810f-f9f577c55196)

from version 6.1.0 to 7.0.0 (Windows 10 and 11)

**Comment by Connoropolous** [comment]
yeah! I think this is the same as #310 !

**Comment by Connoropolous** [comment]
looking at fixing this in the v7 stream of releases

**Comment by TechSupport26** [comment]
> yeah! I think this is the same as #310 !

Yes you are absolutely right.
I don't know if knew what the cause was but I think it was having a project that the user had not joined but was trying to sync, if you get what I am saying.

**Comment by Connoropolous** [comment]
yes, I believe that's exactly it

**Comment by TechSupport26** [comment]
I suppose we can close this.
