### ISSUE TITLE
case of the missing profiles: dashboard collaborator list,  assignee picker

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#316]
I am not able to assign my self to a card. I can assign others. Can someone else replicate this?
V7.0.0 windows 10 and debian 12
![image](https://github.com/lightningrodlabs/acorn/assets/65631811/875eba31-89ee-4b19-9410-5db0d67178f0)

**Comment by Connoropolous** [comment]
I do see myself. What about on the dashboard, do you see that the number of members looks correct?

<img width="513" alt="Screenshot 2023-08-07 at 4 08 51 PM" src="https://github.com/lightningrodlabs/acorn/assets/1409121/4b5c6b0f-c46a-40b1-9a0b-719496126e73">

<img width="960" alt="Screenshot 2023-08-07 at 4 09 42 PM" src="https://github.com/lightningrodlabs/acorn/assets/1409121/70cd0945-aba9-46b8-ab0d-4b259256660f">

**Comment by TechSupport26** [comment]
The number of members is correct but my user is not visible on the dashboard.

I wonder what is causing my profile to not load. I don't believe that it is specific projects as I have projects that were from the previous version 6.1.0 and a new one created in v7.0.0 with my user not showing in either project.

**Comment by Connoropolous** [comment]
ok interesting. 
if you create a new project, does your avatar appear in the member list on the dashboard for that project?

**Comment by TechSupport26** [comment]
No. This is for both windows and debian.

**Comment by Connoropolous** [comment]
it seems this issue might best be reframed as 'case of the missing profiles' since it appears on the dash as well, and in the other places you'd expect to see the profile listed.

**Comment by TechSupport26** [comment]
This is fixed in version 8.0.0

To have a user appear you need to either add a profile picture or enter some text in the Profile Settings so that Acorn tries to get the image. Then you can remove the text and the user will stay visible.
