### ISSUE TITLE
User is Always online in Assignees

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#317]
Bug:
It appears that a user will always appear online in the assignees tab.

![image](https://github.com/lightningrodlabs/acorn/assets/65631811/92da086d-27aa-482f-82ae-bd1cc30dede0)

What is expected. The status to update reflecting the users status

Acorn v7.0.0

Thanks.

**Comment by Connoropolous** [comment]
Yes, you're correct. Reproduced this! Thanks for logging! 

Fix coming soon.

**Comment by Connoropolous** [comment]
should be fixed in https://github.com/lightningrodlabs/acorn/releases/tag/v7.0.1-alpha which does not require migration
