### ISSUE TITLE
v7 Crash when clicking on Ellipsis' under each Project

### ISSUE THREAD

**Issue by MvF-Evangelista** [lightningrodlabs/acorn#318]
Immediately after clicking on the ellipsis' of any of the 4 projects I have loaded in Acorn, the system crashes.  When it reloads, and I try again, it crashes.

See Screen Shot...

<img width="1492" alt="Screenshot 2023-08-06 at 11 16 38 PM" src="https://github.com/lightningrodlabs/acorn/assets/20306239/3bc67f67-8772-4002-9f3c-286eeea5ab08">

**Comment by Connoropolous** [comment]
Thanks for reporting. Yes I can reproduce this. We can easily and quickly fix it and other minor bugs in a minor release.

**Comment by Connoropolous** [comment]
fix for this will be out soon

**Comment by Connoropolous** [comment]
should be fixed in https://github.com/lightningrodlabs/acorn/releases/tag/v7.0.1-alpha which does not require migration

**Comment by MvF-Evangelista** [comment]
Install was clean and seems stable so far – thank you for being so responsive and fixing the bugs I submitted!  Top-notch work there!

From: Connor Turland ***@***.***>
Date: Wednesday, August 9, 2023 at 2:06 PM
To: lightningrodlabs/acorn ***@***.***>
Cc: Mark Franks ***@***.***>, Author ***@***.***>
Subject: Re: [lightningrodlabs/acorn] v7 Crash when clicking on Ellipsis' under each Project (Issue #318)

should be fixed in https://github.com/lightningrodlabs/acorn/releases/tag/v7.0.1-alpha which does not require migration

**Comment by Connoropolous** [comment]
great! You're welcome.
