### ISSUE TITLE
Not Really A Bug:  If you are given a Secret to a project you already have...

### ISSUE THREAD

**Issue by MvF-Evangelista** [lightningrodlabs/acorn#322]
As the title suggests, this is not a bug, per se.  But... it's an issue I would love to see addressed.

If someone invites you to join a project and they are not specific about it (Project Name) and share the secret for you to join and you already have the project, you get an error: **"There was an error joining project: undefined"**

Screenshot:

![image](https://github.com/lightningrodlabs/acorn/assets/20306239/2a93d0e3-0be5-4189-9754-358d816177c8)

It would be great if the error would be more specific... something like:  Error, you are already a member of project "x". Would you like to open Project "x"?  Yes | No (button).

**Comment by Connoropolous** [comment]
I think that's fair to call it a bug. very fixable. 
it's going in the queue.

**Comment by Connoropolous** [comment]
fixed now. Users will not be allowed to 'rejoin' a project they've already joined.
