### ISSUE TITLE
Syncing indicator rotation

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#328]
Minor UI issue

When syncing, the arrows do not match up with rotation direction. Rotating clockwise when the arrows point in the anticlockwise direction.

I have no preference of the direction of rotation but I believe that is is common for the rotation to be clockwise so I would say to change the direction of the arrows.

version 7.1.0
Windows and linux

**Comment by TechSupport26** [comment]
I think as this is in the same area, I am getting this issue.

![image](https://github.com/lightningrodlabs/acorn/assets/65631811/148efa41-4412-4e07-8eee-a3a48fc00175)

`"Conductor returned an error while using a ConductorApi: HolochainP2pError(Other(RoutingSpaceError(KitsuneSpace(0x9b09b4fdb69fd214afec4b6313d83564fa2001603ff2be5c546a08c110b407a394fe2464))))"`

**Comment by Connoropolous** [comment]
@pegahvaezi didn't you do this, I think?

**Comment by pegahvaezi** [comment]
yes this is done now
