### ISSUE TITLE
Version 8.0.1-alpha:  Cannot Synch Projects

### ISSUE THREAD

**Issue by MvF-Evangelista** [lightningrodlabs/acorn#331]
I am not able to synch projects -- whether they are mine or another individual's.  I created a new test project for you to test with me with the following secret:

**absinthe ditch ground pavestone hull**

Please try to synch this project.

Thanks,

Mark

**Comment by TechSupport26** [comment]
I am trying to sync now.

**Comment by TechSupport26** [comment]
@MvF-Evangelista 
I am now on version 8.1.0
If you chose to update to this version check if the secret is the same and @ me when you have acorn open.

Thanks.

**Comment by TechSupport26** [comment]
It worked. I have joined your project. I think.

Is it called Test Project - 8.x

**Comment by pegahvaezi** [comment]
@Connoropolous shall we close this issue?

**Comment by Connoropolous** [comment]
Yes
