### ISSUE TITLE
My Projects page does not auto update

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#332]
The My Projects page does not update when something "new" happens.

When you join a project it will not appear until you refresh the page.
This also applies for members profiles appearing (Indicating that someone has joined the project).

If I remember correctly it will update the amount of members in the project.

**Comment by pegahvaezi** [comment]
@Connoropolous can we make the dashboard page auto-refresh after a project is updated?

**Comment by Connoropolous** [comment]
this should be solved in the next release

**Comment by TechSupport26** [comment]
> this should be solved in the next release

I believe that this is the case.
Thanks.

Also, nice work on the my projects page. Everything looks a bit more defined.
