### ISSUE TITLE
Change the default export file name.

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#333]
Feature request

When exporting a project can the file name be the project name instead of acorn-project as it is rather hard to distinguish what project it is unless you rename them.

Eg. I have the following project called TechSupport26's project. When I export it the name for the project will be TechSupport26's project.

Something to consider with this is if you already exported TechSupport26's project then you would have to change the name or overwrite the old export. Perhaps adding the current Acorn version to the beginning or end of the file name or having some kind of versioning for those who frequently export their projects. in the same folder.

Thanks.

**Comment by Connoropolous** [comment]
good idea. should be easy to do and add good value
