### ISSUE TITLE
Migration to V9.0.0 error

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#335]
A quick description:
I have attempted to migrate from version 8.2.0 to 9.0.0 by clicking on update now. Then when prompted I downloaded the latest version. closed and ran the new version and after a few moments it got stuck. If you try to refresh you will be greeted with the migration warning screen.
(I can access projects by going back to the previous version)

I get the following error from the developer tools:

![image](https://github.com/lightningrodlabs/acorn/assets/65631811/14abce41-224b-4aea-ab6f-26bf09e934e6)

`Error: Broken reference within 'connections' for 'childActionHash'. Unable to locate the Outcome referred to by the hash: uhCkkW22RdMLFSxHCqLSM_88JFPqrslPmx0v9QdtegU_1MEHyf-wc.
      Please inspect your data file, look for these references, and edit it to fix the
      issue. Then try again.
at <span class="devtools-link" role="link" tabindex="-1" title="webpack://acorn-ui/src/migrating/import/cloneFunctions.ts:110:11" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">cloneFunctions.ts:110:11</span>
at <span class="devtools-link" role="link" tabindex="-1" title="webpack://acorn-ui/src/migrating/import/cloneFunctions.ts:41:19" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">cloneFunctions.ts:41:19</span>
</span>    at Generator.next (&lt;anonymous&gt;)
at fulfilled (<span class="devtools-link" role="link" tabindex="-1" title="webpack://acorn-ui/src/projects/createProject.ts:64:2" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">createProject.ts:64:2</span>)
(anonymous) | @ | VersionUpdateEntering.tsx:85

</span></div>`

From the command prompt nothing stands out but I am including it anyway.

```shell
zeph@zxps13:~/Downloads/Acorn Launcher$ ./Acorn-9.0.0-alpha.appimage 
ACORN_AGENT_NUM NaN
holochain > Looking for passphrase piped to stdin
holochain > Found passphrase, continuing...
holochain > 0
holochain > # lair-keystore connection_url # unix:///home/zeph/.config/acorn/keystore-7/socket?k=hWOvY9qA7zEi20qNS5N7XoLudx59Of5k07KNKEjaIQU #
holochain > # lair-keystore running #
holochain > 
holochain > ###HOLOCHAIN_SETUP###
holochain > ###ADMIN_PORT:1235###
holochain > ###HOLOCHAIN_SETUP_END###
holochain > DATASTORE_PATH: /home/zeph/.config/acorn/databases-12
holochain > KEYSTORE_PATH: Some("/home/zeph/.config/acorn/keystore-7")
holochain > NETWORK_SEED: None
holochain > Recognized a keypair, using that. The public key is: AgentPubKey(uhCAk1clNg9ZMmvyaK1R_4tgJii0GuzQmazZH39JpXrvmytzs5Hjl)
holochain > There is no app installed, so starting fresh...
holochain > continuing with the installation...
holochain > 4
holochain > Installed, now enabling...
holochain > 5
holochain > 6
holochain > Enabled.
holochain >      APP_WS_PORT: 8889
holochain > INSTALLED_APP_ID: main-app
holochain > HOLOCHAIN_RUNNER_IS_READY
holochain > 7
received checkForMigrationData

``` 

I then get the usual gossip timeout errors and such.

This happens on both Windows and Debian 12.

My first question is can I delete databases 12 and keystore 7

Let me know if I can do anything to help.

**Comment by Connoropolous** [comment]
Oh ok interesting. Thanks for logging. 

Yes, you can delete databases-12 and keystore-7, and continue to use Acorn 8. 

Since it seems like one of your projects is... not quite "corrupted" but is missing data then I think you might have to manually migrate each project one by one, and not use the auto-migration process.

**Comment by TechSupport26** [comment]
You are correct. It was just one project that I have been using recently. When I try to import the project I get the following.

Broken reference within 'connections' for 'childActionHash'. Unable to locate the Outcome referred to by the hash: uhCkkW22RdMLFSxHCqLSM_88JFPqrslPmx0v9QdtegU_1MEHyf-wc. Please inspect your data file, look for these references, and edit it to fix the issue. Then try again.
![image](https://github.com/lightningrodlabs/acorn/assets/65631811/73bf45ce-7215-4f30-b8ce-6db35f69e953)

I was able to import a save from v 7.1.0 so I should be able to continue on.

If you think that it is appropriate to close this then do so as the 'issue' was found.

**Comment by pegahvaezi** [comment]
@Connoropolous should we close this?

**Comment by Connoropolous** [comment]
yes
