### ISSUE TITLE
Project migrated button not functioning

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#347]
In Acorn V9.5.1 the Project Migrated button does not work.
Expected action would be the Project Migrated popup to appear, instead nothing happens.

It does work in v9.4.1

OS Debian 12

Thanks

**Comment by Connoropolous** [comment]
we should be doing a release tomorrow!
Ill try and make sure thats resolved and you can access your v9 projects.

**Comment by TechSupport26** [comment]
I am looking forward to it, if it is what I think is. 😁

**Comment by Connoropolous** [comment]
oh shoot. I am not sure that I double checked this in the 9.6.1 release. If it's still not working, I will try to address asap

**Comment by TechSupport26** [comment]
All good. We are not in a hurry.

**Comment by Connoropolous** [comment]
fix out now in v9.7.1-alpha
