### ISSUE TITLE
Using Ctrl-Enter may be the wrong key combination

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#349]
When creating a new card in Windows 10 and Debian, after tabbing to the scope toast, holding the ctrl key and pressing enter only toggles the scope option, not creating the card until you click outside of the card or move focus to the text, then pressing enter.

Instead, using the windows key + alt + enter works for me. Perhaps this is different for Mac.

**Comment by Connoropolous** [comment]
got it, yes, in fact I mistook the 'meta key' for the Ctrl key on Windows, in fact its the Windows key by the sounds of it. You may not even have to press alt?

**Comment by TechSupport26** [comment]
> You may not even have to press alt?

Yes you are right. In the latest version you only have to press the windows key.

I do feel that pressing the control key may be better than the windows key as when you stop pressing it the windows menu appears if you don't press enter, say a change of mind and you want to keep on writing in the card, where as with the control key, it has no immediate effect on it's own.
Perhaps adding it to the preferences. The user can map the key they want to use for that function...
