### ISSUE TITLE
`npm run dev` lair_keystore work around

### ISSUE THREAD

**Issue by weswalla** [lightningrodlabs/acorn#36]
when running `npm run dev`, you may run into an issue with lair_keystore, where the conductor won't be able to find the keystore location and your terminal will start building the packages.

Here are the steps I took as a workaround to avoid that from occurring:
make sure you have the keystore dependencies. On linux run `sudo apt-get install libsqlcipher-dev`, on Mac run `brew install sqlcipher`.

check to make sure your conductor can find the packaged keystore binary (run each in separate terminals): 
**linux**
`electron/node_modules/electron-holochain/binaries/linux/lair-keystore --lair-dir tmp2/keystore`
`electron/node_modules/electron-holochain/binaries/linux/holochain-runner dna/workdir/profiles.dna --admin-ws-port 1234 --app-id test --app-ws-port 8888 --keystore-path tmp2/keystore` 

**mac**
`electron/node_modules/electron-holochain/binaries/mac/lair-keystore --lair-dir tmp2/keystore`
`electron/node_modules/electron-holochain/binaries/mac/holochain-runner dna/workdir/profiles.dna --admin-ws-port 1234 --app-id test --app-ws-port 8888 --keystore-path tmp2/keystore`

**Comment by pegahvaezi** [comment]
let's move this to a contributors guide and close this
