### ISSUE TITLE
Support multiline content when creating new card

### ISSUE THREAD

**Issue by kaichaosun** [lightningrodlabs/acorn#50]
It's not supported when I testing the latest release.
This feature could be handy for editors like me.

**Comment by kaichaosun** [comment]
Just tried on my macos (10.14.6), shift+enter is not making a new newline, instead it's go out of editing mode.

**Comment by Connoropolous** [comment]
You're right. I just tested, and one way to get multi-line is to open 'Expanded View' by hovering over a goal, clicking on the icon that has 4 outward pointing arrows, and editing the title from that mode. 

You can just use 'Enter' normally for line breaks. It's autosaving, so whenever you click away it will save your new content

**Comment by pegahvaezi** [comment]
Closing this issue since adding line breaks is possible through editing Outcome Statement in the Expanded View.
