### ISSUE TITLE
Zooming results in very small child/parent node buttons

### ISSUE THREAD

**Issue by LifelessRelics** [lightningrodlabs/acorn#53]
This can be reset by using ctrl+0, but if you scroll out using ctrl - many time and then scroll in with ctrl + mouse in, the nodes to create child/parent lines are incredibly small.

**Comment by Connoropolous** [comment]
thanks for the input @LifelessRelics . We will give the same thing you describe to see what you mean

**Comment by pegahvaezi** [comment]
To zoom in and out on the canvas, use one of the following:

- the bottom right zoom buttons (-) and (+)
- OR for Trackpad, Pinch in and out, or hold cmd/ctrl + scroll wheel  (make sure Trackpad option is enabled in your Preferences)
- OR for Mouse, Use mouse wheel, or slide with two fingers up/down, or pinch in/out (make sure Mouse option is enabled in your Preferences)

ctrl +/-  and cmd +/- are usually reserved for accessibility zooming options.

Let us know if that's not what you meant.
