### ISSUE TITLE
After using priority view, Can no longer simply edit boxes in map view

### ISSUE THREAD

**Issue by LifelessRelics** [lightningrodlabs/acorn#54]
I set a few top priorities and returned unable to edit the map box text. Can edit by double clicking. Strange the UI behaves different after using priority view. Can also now have empty boxes after changing the parent of a connected node.

**Comment by Connoropolous** [comment]
We will try to replicate, thanks. Will follow up with any questions

**Comment by pegahvaezi** [comment]
@LifelessRelics closing this now since we haven't been able to replicate the issue in the new version (1.0.2-alpha). There are also major changes and updates to Acorn in this release. Please try the newest release and open a new issue if the issue still persists for you.
