### ISSUE TITLE
No way to remove users from a project

### ISSUE THREAD

**Issue by adamth0mps0n** [lightningrodlabs/acorn#63]
There appears to be no way to remove users from a project.

**Comment by adamth0mps0n** [comment]
Latest version 0.5.7 still has no way to remove users or delete projects for that matter.. Perhaps a Throw-away DHT??

**Comment by Connoropolous** [comment]
@adamth0mps0n 
the best way to remove someone at this time would be to export the project as JSON, and then re-import it.

This will generate a new secret code and a new DHT. 
Re-invite the folks to that project that should still have access. 

Everything will carry over fairly cleanly, although we would be interested to hear about your thoughts and experiences of doing so!

**Comment by Connoropolous** [comment]
@adamth0mps0n we've taken down notes today on your feedback, and we are looking into the 'delete projects' feature which would be quite useful, and is distinct from 'remove user from project'

**Comment by Connoropolous** [comment]
I don't think there will ever be a way to 'remove users from project', necessarily, due to inherited realities of holochain
