### ISSUE TITLE
App stuck in loading after I try to join a already added project

### ISSUE THREAD

**Issue by felri** [lightningrodlabs/acorn#7]
Create a project, copy the password
Click on join project and paste the password
App gets stuck in loading 

I tried to reinstall the app but when I try to get back it has the same error, so I can't test anymore because I'm stuck at the loading project screen

**Comment by Connoropolous** [comment]
Hi @felri 

How come you would to try to join the same project on your own same device? If thats whats happening. 

Join project is meant for joining someone else's project.

**Comment by Connoropolous** [comment]
Thanks! Thats very useful.

 It is running holochain on your device yes, not hosted like Holo. 

If you want to see joining a project in action, best to have a collaborator or contact create a project and have you join. I can share a project with you

**Comment by felri** [comment]
I would love to check a shared project, can you help me make the app work again? I''m stuck in this screen even after a reinstall, maybe I need to delete something and start again.

<img width="1109" alt="Captura de Tela 2021-05-09 às 09 58 52" src="https://user-images.githubusercontent.com/56592364/117573241-2adeb000-b0ad-11eb-9415-17d8683e71c0.png">

**Comment by Connoropolous** [comment]
Yes ok, so open Finder, then go to Go To Folder in the menu system. 

There, type in

~/Library/Application Support/Acorn

And go. In that folder, delete everything in there. 

Relaunch Acorn. You should be fine, but you will have no projects and lose any data, so beware of that. Have you created anything valuable or just testing?

**Comment by felri** [comment]
Working fine again, nothing important was lost, can you share a project?

**Comment by Connoropolous** [comment]
Yeah sure. Had to get to my computer and get one open... 

`dig parabola oxygen pointy pebbly`

**Comment by pegahvaezi** [comment]
Closing since this a non-issue at the moment. 
In the future we could add a prevention error for Join a Project secret field to prevent users from using the secrets for the projects they are already a member of.
