### ISSUE TITLE
Problems rendering some characters

### ISSUE THREAD

**Issue by apalmer27516** [lightningrodlabs/acorn#77]
This is probably just a local problem, but I noticed the "i" renders fine in most situations, except when it follows an "f" and then the dot at the top doesn't print. This is running on Ubuntu with the 0.5.9 AppImage.
![Screenshot from 2022-01-24 08-34-29](https://user-images.githubusercontent.com/32514218/150792762-e032b05d-605d-4e12-b60e-3a3279b590e9.png)

**Comment by Connoropolous** [comment]
Thanks for logging, we will take a look for it on various systems.

**Comment by pegahvaezi** [comment]
Hi @apalmer27516, this issue should have been fixed in the newest release (v.1.1.0-alpha). Please let us know if the issue still persists after updating to the newest release.

**Comment by apalmer27516** [comment]
Interesting, I still see the issue before a new item has saved, but then it is fixed. It doesn't occur in the detail box when modifying the title, but the rendering error does show when drafting and displaying the text in the description. It also occurs when typing in the search box, but not in the search results list.
