### ISSUE TITLE
Dialog doesn't close after single value selection

### ISSUE THREAD

**Issue by apalmer27516** [lightningrodlabs/acorn#78]
This might be by design, but I thought it might be an oversight that when selecting a status or hierarchy from the bottom of the main window (or the detailed edit window) and then changing the single value, it doesn't close the dialog box. For the entry point selection, it closes the dialog and goes to the entry point which seems to be fast and clear and the status and hierarchy could work the same.

**Comment by Connoropolous** [comment]
This is out of date per the new 1.0.x versions
